project = "debug_70m_zero_band"

model_name = "70M"
model_type = "llama2"

[hardware]
micro_batch_size = 64
reshard_after_forward = false

[train]
batch_size = 512

[data]
seq_length = 1024
dataset_name_or_paths = "datasets/fineweb-edu"

[diloco]
inner_steps = 16
delayed_update = true

[pccl]
ccoip_host = "127.0.0.1:48148"