name_model = "10B"
project = "10B_zero_band"
wandb_resume = true

[train]
micro_bs = 1
ac_ckpt = true

[optim]
sched_type = "wsd-sqrt"
batch_size = 128 #1M tokens bs
warmup_steps = 1000
total_steps = 1_000_000_000_000
lr = 7.5e-5

adam_betas1 = 0.9
adam_betas2 = 0.95
weight_decay = 0.1

z_loss = true

[data]
seq_length = 8192
dataset_name_or_paths = "PrimeIntellect/fineweb-edu,PrimeIntellect/fineweb"
dataset_ratio = "55:45"
num_workers = 1
reverse_data_files = true

[diloco]
inner_steps = 100
compression = "uint8"

[ckpt]
interval = 100
topk = 40
path = "outputs_10B_zero_band"
remote_data_path = "gs://checkpoints_pi/10b/data/"
