project = "debug_10B_zero_band"
model_name = "10B"
model_type = "llama3"

[hardware]
micro_batch_size = 1
act_ckpt = true

[train]
batch_size = 128 #1M tokens bs

[train.lr_scheduler]
decay_type = "sqrt"
lr = 7.5e-5
end_lr = 0.0
num_warmup_steps = 1000
num_decay_steps = 1_000_000_000_000

[train.optimizer]
type = 'adamw'
betas1 = 0.9
betas2 = 0.95
weight_decay = 0.1

[data]
seq_length = 8192
num_workers = 4
