name_model = "10B" # "26B"
type_model = "llama2"

project = "debug_I2_zero_band"
run_name = "testing :3"

metric_logger_type = "dummy" # "wandb"
log_level = "DEBUG"

log_all_rank = false


[train]
micro_bs = 1
ac_ckpt = true
torch_profiler = false
torch_compile = true
fused_linear_ce = true
fsdp_cpu_offload = true

[train.memory_profiler]
freq = 1
snapshot_dir = "logs/"

[optim]
sched_type = "wsd-sqrt"
batch_size = 128
warmup_steps = 0
total_steps = 5 # 2_000
z_loss = true

[data]
seq_length = 8192
num_workers = 4
