name_model = "10B"
project = "debug_I2_zero_band"
metric_logger_type = "dummy"

[train]
micro_bs = 1
ac_ckpt = true
torch_profiler = false

[train.memory_profiler]
freq = 1
snapshot_dir = "logs/"

[optim]
sched_type = "wsd-sqrt"
batch_size = 128 #1M tokens bs
warmup_steps = 0
total_steps = 1
lr = 7.5e-5
num_chunks = 8

adam_betas1 = 0.9
adam_betas2 = 0.95
weight_decay = 0.1

z_loss = true

[data]
seq_length = 8192
num_workers = 4
