name_model = "10B" # "150M"
# type_model = "llama3"

project = "debug_I2_zero_band"
run_name = "Liger 150M"

metric_logger_type = "dummy" # "wandb"
log_level = "DEBUG"


[train]
micro_bs = 1
ac_ckpt = true
torch_profiler = false
torch_compile = true
fused_linear_ce = false

[train.memory_profiler]
freq = 1
snapshot_dir = "logs/"

[optim]
sched_type = "wsd-sqrt"
batch_size = 128 #1M tokens bs
warmup_steps = 0
total_steps = 1 # 2_000
num_chunks = 8
z_loss = false

[data]
seq_length = 8192
num_workers = 4
