"""Prime Intellect Sandboxes SDK.

A standalone SDK for managing remote code execution environments (sandboxes).
Includes HTTP client, authentication, and full sandbox lifecycle management.
"""

from .core import (
    APIClient,
    APIError,
    APITimeoutError,
    AsyncAPIClient,
    Config,
    PaymentRequiredError,
    UnauthorizedError,
)
from .exceptions import (
    BatchStatusUnsupportedError,
    CommandTimeoutError,
    DownloadTimeoutError,
    SandboxFileNotFoundError,
    SandboxFileTooLargeError,
    SandboxImagePullError,
    SandboxNotRunningError,
    SandboxOOMError,
    SandboxTimeoutError,
    UploadTimeoutError,
)
from .images import AsyncImageClient, ImageClient
from .models import (
    AdvancedConfigs,
    BackgroundJob,
    BackgroundJobStatus,
    BackgroundJobStatusSnapshot,
    BatchSandboxStatusResponse,
    BuildImageRequest,
    BuildImageResponse,
    BulkBuildImageResponse,
    BulkDeleteSandboxRequest,
    BulkDeleteSandboxResponse,
    CommandResponse,
    CreateSandboxRequest,
    EgressPolicyStatus,
    FileUploadResponse,
    ImageArtifactType,
    ImageBuildStatus,
    ImageCoordinateState,
    ImageListItem,
    ImageListResponse,
    ImageMutationError,
    ImageOwner,
    ImageOwnerType,
    ImageUpdateItem,
    ImageUpdatePatch,
    ImageUpdateResult,
    ImageUpdateSource,
    ImageVisibility,
    PersonalImageOwner,
    PlatformImageOwner,
    ReadFileResponse,
    Sandbox,
    SandboxEgressPolicy,
    SandboxListResponse,
    SandboxStatus,
    SandboxStatusLookupError,
    SandboxStatusSnapshot,
    SourceImageBuildResult,
    SSHSession,
    StartCommand,
    TeamImageOwner,
    UpdateImagesRequest,
    UpdateImagesResponse,
)
from .process import AsyncSandboxProcess
from .sandbox import AsyncSandboxClient, SandboxClient

__version__ = "0.3.0"

# Deprecated alias for backward compatibility
TimeoutError = APITimeoutError

__all__ = [
    # Core HTTP Client & Config
    "APIClient",
    "AsyncAPIClient",
    "Config",
    # Sandbox Clients
    "SandboxClient",
    "AsyncSandboxClient",
    "AsyncSandboxProcess",
    "ImageClient",
    "AsyncImageClient",
    # Models
    "Sandbox",
    "SandboxEgressPolicy",
    "SandboxStatus",
    "SandboxListResponse",
    "CreateSandboxRequest",
    "StartCommand",
    "CommandResponse",
    "FileUploadResponse",
    "ReadFileResponse",
    "BulkDeleteSandboxRequest",
    "BulkDeleteSandboxResponse",
    "EgressPolicyStatus",
    "AdvancedConfigs",
    "BackgroundJob",
    "BackgroundJobStatus",
    "BackgroundJobStatusSnapshot",
    "BatchSandboxStatusResponse",
    "SandboxStatusSnapshot",
    "SandboxStatusLookupError",
    "SSHSession",
    "BuildImageRequest",
    "BuildImageResponse",
    "BulkBuildImageResponse",
    "SourceImageBuildResult",
    "ImageVisibility",
    "ImageBuildStatus",
    "ImageArtifactType",
    "ImageOwnerType",
    "ImageListItem",
    "ImageListResponse",
    "ImageOwner",
    "PersonalImageOwner",
    "TeamImageOwner",
    "PlatformImageOwner",
    "ImageUpdateSource",
    "ImageUpdatePatch",
    "ImageUpdateItem",
    "UpdateImagesRequest",
    "UpdateImagesResponse",
    "ImageUpdateResult",
    "ImageCoordinateState",
    "ImageMutationError",
    # Exceptions
    "APIError",
    "BatchStatusUnsupportedError",
    "UnauthorizedError",
    "PaymentRequiredError",
    "SandboxFileNotFoundError",
    "SandboxFileTooLargeError",
    "APITimeoutError",
    "TimeoutError",  # Deprecated alias
    "SandboxOOMError",
    "SandboxTimeoutError",
    "SandboxImagePullError",
    "SandboxNotRunningError",
    "CommandTimeoutError",
    "UploadTimeoutError",
    "DownloadTimeoutError",
]
