"""Prime Intellect Sandboxes SDK.

A standalone SDK for managing remote code execution environments (sandboxes).
Includes HTTP client, authentication, and full sandbox lifecycle management.
"""

from .core import (
    APIClient,
    APIError,
    APITimeoutError,
    AsyncAPIClient,
    Config,
    PaymentRequiredError,
    UnauthorizedError,
)
from .exceptions import (
    BatchStatusUnsupportedError,
    CommandTimeoutError,
    DownloadTimeoutError,
    SandboxFileNotFoundError,
    SandboxFileTooLargeError,
    SandboxImagePullError,
    SandboxNotRunningError,
    SandboxOOMError,
    SandboxTimeoutError,
    UploadTimeoutError,
)
from .images import AsyncImageClient, ImageClient
from .models import (
    AdvancedConfigs,
    BackgroundJob,
    BackgroundJobStatus,
    BackgroundJobStatusSnapshot,
    BatchSandboxStatusResponse,
    BuildImageRequest,
    BuildImageResponse,
    BulkDeleteSandboxRequest,
    BulkDeleteSandboxResponse,
    BulkImageTransferResponse,
    CommandRequest,
    CommandResponse,
    CreateSandboxRequest,
    DockerImageCheckResponse,
    EgressPolicyStatus,
    ExposedPort,
    ExposePortRequest,
    FileUploadResponse,
    ImageArtifactType,
    ImageBuildStatus,
    ImageCoordinateState,
    ImageListItem,
    ImageListResponse,
    ImageMutationError,
    ImageOwner,
    ImageOwnerType,
    ImageUpdateItem,
    ImageUpdatePatch,
    ImageUpdateResult,
    ImageUpdateSource,
    ImageVisibility,
    ListExposedPortsResponse,
    PersonalImageOwner,
    PlatformImageOwner,
    ReadFileResponse,
    RegistryCredentialSummary,
    Sandbox,
    SandboxEgressPolicy,
    SandboxListResponse,
    SandboxStatus,
    SandboxStatusLookupError,
    SandboxStatusSnapshot,
    SSHSession,
    StartCommand,
    TeamImageOwner,
    TransferImageResult,
    UpdateImagesRequest,
    UpdateImagesResponse,
    UpdateSandboxRequest,
)
from .process import AsyncSandboxProcess
from .sandbox import AsyncSandboxClient, AsyncTemplateClient, SandboxClient, TemplateClient

__version__ = "0.2.40"

# Deprecated alias for backward compatibility
TimeoutError = APITimeoutError

__all__ = [
    # Core HTTP Client & Config
    "APIClient",
    "AsyncAPIClient",
    "Config",
    # Sandbox Clients
    "SandboxClient",
    "AsyncSandboxClient",
    "AsyncSandboxProcess",
    "TemplateClient",
    "AsyncTemplateClient",
    "ImageClient",
    "AsyncImageClient",
    # Models
    "Sandbox",
    "SandboxEgressPolicy",
    "SandboxStatus",
    "SandboxListResponse",
    "CreateSandboxRequest",
    "StartCommand",
    "UpdateSandboxRequest",
    "CommandRequest",
    "CommandResponse",
    "FileUploadResponse",
    "ReadFileResponse",
    "BulkDeleteSandboxRequest",
    "BulkDeleteSandboxResponse",
    "RegistryCredentialSummary",
    "DockerImageCheckResponse",
    "EgressPolicyStatus",
    "AdvancedConfigs",
    "BackgroundJob",
    "BackgroundJobStatus",
    "BackgroundJobStatusSnapshot",
    "BatchSandboxStatusResponse",
    "SandboxStatusSnapshot",
    "SandboxStatusLookupError",
    "BuildImageRequest",
    "BuildImageResponse",
    "BulkImageTransferResponse",
    "TransferImageResult",
    "ImageVisibility",
    "ImageBuildStatus",
    "ImageArtifactType",
    "ImageOwnerType",
    "ImageListItem",
    "ImageListResponse",
    "ImageOwner",
    "PersonalImageOwner",
    "TeamImageOwner",
    "PlatformImageOwner",
    "ImageUpdateSource",
    "ImageUpdatePatch",
    "ImageUpdateItem",
    "UpdateImagesRequest",
    "UpdateImagesResponse",
    "ImageUpdateResult",
    "ImageCoordinateState",
    "ImageMutationError",
    # Port Forwarding
    "ExposePortRequest",
    "ExposedPort",
    "ListExposedPortsResponse",
    "SSHSession",
    # Exceptions
    "APIError",
    "BatchStatusUnsupportedError",
    "UnauthorizedError",
    "PaymentRequiredError",
    "SandboxFileNotFoundError",
    "SandboxFileTooLargeError",
    "APITimeoutError",
    "TimeoutError",  # Deprecated alias
    "SandboxOOMError",
    "SandboxTimeoutError",
    "SandboxImagePullError",
    "SandboxNotRunningError",
    "CommandTimeoutError",
    "UploadTimeoutError",
    "DownloadTimeoutError",
]
