name_model = "1B"
project = "debug_1B_zero_band"
type_model = "llama2"

[train]
micro_bs = 16  

[optim]
batch_size = 2048
warmup_steps = 1000
total_steps = 88_000

z_loss = true

[optim.optim]
lr = 4e-4


[diloco]
inner_steps = 50
compression = "uint8"

[ckpt]
interval = 50
topk = 3
path = "outputs_1b_diloco_50"

