import asyncio
import fcntl
import logging
import os
import re
import subprocess
import threading
import time
from pathlib import Path
from typing import Optional

import httpx

from prime_tunnel.binary import get_frpc_path
from prime_tunnel.core.client import TunnelClient
from prime_tunnel.exceptions import (
    TunnelConnectionError,
    TunnelError,
    TunnelGoneError,
    TunnelTimeoutError,
)
from prime_tunnel.models import TunnelInfo, TunnelStatus

# timestamp + level + caller prefix + message
_LOG_RE = re.compile(
    r"\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3}\s"
    r"\[([EWIDT])\]\s"
    r"\[.*?\]\s"
    r"(?:\[.*?\]\s)*"
    r"(.+)"
)
_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")

frpc_logger = logging.getLogger("prime_tunnel.frpc")

_FRPC_LEVELS = {
    "E": logging.ERROR,
    "W": logging.WARNING,
    "I": logging.INFO,
    "D": logging.DEBUG,
    "T": logging.DEBUG,
}


def _log_frpc_line(raw_line: str, tunnel_id: str | None) -> None:
    """Forward one frpc output line to the prime_tunnel.frpc logger at its own level."""
    line = _ANSI_RE.sub("", raw_line)
    m = _LOG_RE.match(line)
    if m:
        level, msg = _FRPC_LEVELS.get(m.group(1), logging.INFO), m.group(2)
    else:
        level, msg = logging.INFO, line
    frpc_logger.log(level, "frpc %s: %s", tunnel_id or "-", msg)


# Rejection reasons that mean the registration itself can no longer be used.
_GONE_ERRORS = (
    "tunnel is inactive",
    "tunnel not registered",
)

# Statuses the tunnel service never leaves.
_TERMINAL_STATUSES = ("expired", "terminated")


def _parse_frpc_error(
    output_lines: list[str],
    tunnel_id: str | None = None,
    return_code: int | None = None,
) -> TunnelConnectionError:
    """Parse frpc log output into a structured tunnel exception."""
    error_messages: list[str] = []
    for raw_line in output_lines:
        line = _ANSI_RE.sub("", raw_line)
        m = _LOG_RE.match(line)
        if not m:
            continue
        level, msg = m.group(1), m.group(2)
        if level in ("E", "W"):
            error_messages.append(msg)

    if error_messages:
        message = error_messages[-1]
    else:
        output_text = "\n".join(output_lines) if output_lines else "(no output captured)"
        exit_info = f" (exit code {return_code})" if return_code is not None else ""
        message = f"frpc process failed{exit_info}: {output_text}"

    if any(reason in message.lower() for reason in _GONE_ERRORS):
        return TunnelGoneError(tunnel_id=tunnel_id, message=message)
    return TunnelConnectionError(tunnel_id=tunnel_id, message=message)


# Server-side rejection reasons that retrying can never fix.
_FATAL_LOGIN_ERRORS = _GONE_ERRORS + (
    "invalid binding secret",
    "invalid authentication token",
    "token in login doesn't match",
)


def _scan_startup_line(line: str) -> Optional[str]:
    """Classify an frpc startup log line.

    Returns "connected" once the proxy is registered, "fatal" for login
    failures that cannot succeed on retry and for a proxy the server refused
    to start, and None for anything else (including transient login/connect
    failures frpc will retry).
    """
    lowered = line.lower()
    if "start proxy success" in lowered:
        return "connected"
    if "login to the server failed" in lowered or "connect to server error" in lowered:
        if any(reason in lowered for reason in _FATAL_LOGIN_ERRORS):
            return "fatal"
    # frpc only retries a refused proxy after 30s, so report it now.
    if "start error" in lowered:
        return "fatal"
    return None


def _reports_gone(line: str) -> bool:
    """Whether an frpc log line says the server rejected the registration as gone."""
    lowered = line.lower()
    if not any(
        marker in lowered
        for marker in ("login to the server failed", "connect to server error", "start error")
    ):
        return False
    return any(reason in lowered for reason in _GONE_ERRORS)


class Tunnel:
    """Tunnel interface for exposing local services."""

    def __init__(
        self,
        local_port: int,
        local_addr: str = "127.0.0.1",
        name: Optional[str] = None,
        connection_timeout: float = 30.0,
        log_level: str = "info",
        team_id: Optional[str] = None,
        labels: Optional[list[str]] = None,
        http_user: Optional[str] = None,
    ):
        """
        Initialize a tunnel.

        Args:
            local_port: Local port to tunnel
            local_addr: Local address to tunnel (default: 127.0.0.1)
            name: Optional friendly name for the tunnel
            team_id: Optional team ID for team tunnels
            labels: Optional labels for organizing tunnels
            connection_timeout: Timeout for establishing connection (seconds)
            log_level: frpc log level (trace, debug, info, warn, error)
            http_user: Optional HTTP basic auth username protecting tunnel
                traffic. The password is auto-generated by the backend;
                read it from the http_password property after start().
        """
        self.local_port = local_port
        self.local_addr = local_addr
        self.name = name
        self.team_id = team_id
        self.labels = labels or []
        self.connection_timeout = connection_timeout
        self.log_level = log_level
        self.http_user = http_user

        self._client = TunnelClient()
        self._process: Optional[subprocess.Popen] = None
        self._tunnel_info: Optional[TunnelInfo] = None
        self._config_file: Optional[Path] = None
        self._started = False
        self._stopping = False
        self._gone = False
        # Serializes start() and restart().
        self._process_lock = asyncio.Lock()
        self._output_lines: list[str] = []

    @property
    def tunnel_id(self) -> Optional[str]:
        """Get the tunnel ID."""
        return self._tunnel_info.tunnel_id if self._tunnel_info else None

    @property
    def url(self) -> Optional[str]:
        """Get the tunnel URL."""
        return self._tunnel_info.url if self._tunnel_info else None

    @property
    def hostname(self) -> Optional[str]:
        """Get the tunnel hostname."""
        return self._tunnel_info.hostname if self._tunnel_info else None

    @property
    def http_password(self) -> Optional[str]:
        """Get the auto-generated basic auth password (set after start()).

        Only available on the Tunnel instance that created the registration;
        it cannot be retrieved again later.
        """
        return self._tunnel_info.http_password if self._tunnel_info else None

    @property
    def is_running(self) -> bool:
        """Check if the tunnel is running."""
        if self._process is None:
            return False
        return self._process.poll() is None

    @property
    def is_gone(self) -> bool:
        """Whether the registration is known to be unusable. Makes no API call.

        Set when the tunnel service rejects frpc because the tunnel was
        deleted, expired, or stayed disconnected for too long, or when
        status() finds the same. restart() cannot bring such a tunnel back:
        stop it and start a new one.
        """
        return self._gone

    async def check_registered(self) -> bool:
        """Check if the tunnel's registration can still be used.

        Calls get_tunnel() on the backend API. Returns False if the service
        has no record of the tunnel or reports it expired or terminated.

        Raises TunnelError/TunnelTimeoutError on transient API failures
        so the caller can distinguish "tunnel gone" from "API unreachable".
        """
        if self._tunnel_info is None:
            return False
        info = await self._client.get_tunnel(self._tunnel_info.tunnel_id)
        return info is not None and (info.status or "").lower() not in _TERMINAL_STATUSES

    async def status(self) -> TunnelStatus:
        """
        Report the local frpc process and the tunnel service's record.

        A registration the service reports as connected is not proof that
        the URL is serving; disconnected, expired and terminated are reliable.

        Returns:
            TunnelStatus for this tunnel

        Raises:
            TunnelError: If the tunnel is not started or the API call fails
            TunnelTimeoutError: If the API call times out
        """
        if self._tunnel_info is None:
            raise TunnelError("Tunnel is not started")
        tunnel_id = self._tunnel_info.tunnel_id
        info = await self._client.get_tunnel(tunnel_id)
        registration = None
        if info is not None and info.status:
            registration = info.status.lower()
        if info is None or registration in _TERMINAL_STATUSES:
            self._gone = True
        return TunnelStatus(
            tunnel_id=tunnel_id,
            running=self.is_running,
            registration=registration,
            gone=self._gone,
        )

    async def start(self) -> str:
        """
        Start the tunnel.

        Returns:
            The tunnel URL

        Raises:
            TunnelError: If tunnel registration fails
            TunnelConnectionError: If frpc fails to connect or tunnel is not running
            TunnelTimeoutError: If connection times out
        """
        if self._started:
            raise TunnelError("Tunnel is already started")

        async with self._process_lock:
            if self._started:
                raise TunnelError("Tunnel is already started")
            self._stopping = False
            return await self._register_and_connect()

    async def _register_and_connect(self) -> str:
        """Register the tunnel, start frpc and wait for it to connect."""
        self._gone = False
        # 1. Get frpc binary
        frpc_path = await asyncio.to_thread(get_frpc_path)

        # 2. Register tunnel with backend
        try:
            self._tunnel_info = await self._client.create_tunnel(
                local_port=self.local_port,
                name=self.name,
                team_id=self.team_id,
                labels=self.labels,
                http_user=self.http_user,
            )
        except BaseException as e:
            await self._cleanup()
            if isinstance(e, (asyncio.CancelledError, TunnelError)):
                raise
            raise TunnelError(f"Failed to register tunnel: {e}") from e

        # 3. Generate frpc config
        try:
            self._config_file = self._write_frpc_config()
        except BaseException as e:
            await self._cleanup()
            if isinstance(e, asyncio.CancelledError):
                raise
            raise TunnelError(f"Failed to write frpc config: {e}") from e

        # 4. Start frpc process
        try:
            self._process = subprocess.Popen(
                [str(frpc_path), "-c", str(self._config_file)],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
        except BaseException as e:
            await self._cleanup()
            if isinstance(e, asyncio.CancelledError):
                raise
            raise TunnelConnectionError(message=f"Failed to start frpc: {e}") from e

        # 5. Wait for connection
        try:
            await self._wait_for_connection()
        except BaseException:
            await self._cleanup()
            raise

        # 6. Start background thread to drain pipes (prevents buffer exhaustion)
        try:
            self._start_pipe_drain()
        except BaseException as e:
            await self._cleanup()
            if isinstance(e, asyncio.CancelledError):
                raise
            raise TunnelConnectionError(message=f"Failed to start pipe drain: {e}") from e

        self._started = True

        return self.url

    async def restart(self) -> str:
        """
        Restart frpc, keeping the tunnel's registration and URL.

        If the restart fails, the tunnel stays registered with no frpc
        running: call restart() again or stop(). A tunnel that was deleted,
        expired, or stayed disconnected for too long cannot be restarted.

        Returns:
            The tunnel URL

        Raises:
            TunnelError: If the tunnel is not started or is stopped meanwhile
            TunnelGoneError: If the registration can no longer be used
            TunnelConnectionError: If frpc fails to start or connect
            TunnelTimeoutError: If connection times out
        """
        if not self._started or self._stopping:
            raise TunnelError("Tunnel is not started")

        async with self._process_lock:
            if not self._started or self._stopping:
                raise TunnelError("Tunnel is not started")

            url = self.url
            frpc_path = await asyncio.to_thread(get_frpc_path)

            old_process, self._process = self._process, None
            if old_process is not None:
                await asyncio.to_thread(self._end_process, old_process, kill=True)

            if self._stopping:
                raise TunnelError("Tunnel was stopped during restart")

            try:
                process = subprocess.Popen(
                    [str(frpc_path), "-c", str(self._config_file)],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                )
            except Exception as e:
                raise TunnelConnectionError(message=f"Failed to start frpc: {e}") from e
            self._process = process

            stopped = TunnelError("Tunnel was stopped during restart")
            try:
                # A stop during launch saw no process to end.
                if self._stopping:
                    raise stopped
                await self._wait_for_connection(process)
                if self._stopping:
                    raise stopped
                self._gone = False
                self._start_pipe_drain(process)
            except BaseException as e:
                if isinstance(e, TunnelGoneError):
                    self._gone = True
                await asyncio.to_thread(self._end_process, process, kill=True)
                # Show the failed frpc's output, not the old one's.
                if hasattr(self, "_output_lock"):
                    with self._output_lock:
                        self._recent_output = list(self._output_lines[-50:])
                if not self._stopping or not isinstance(e, Exception):
                    raise
                self._process = None
                if e is stopped:
                    raise
                raise stopped from e

            return url

    @staticmethod
    def _end_process(process: subprocess.Popen, kill: bool = False) -> None:
        """Terminate frpc, or kill it at once if `kill` is set."""
        try:
            if kill:
                process.kill()
                process.wait(timeout=2)
                return
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=2)
        except Exception:
            pass

    async def stop(self) -> None:
        """Stop the tunnel and cleanup resources."""
        if not self._started:
            return

        self._stopping = True
        await self._cleanup()
        self._started = False

    def sync_stop(self) -> None:
        """Stop the tunnel synchronously. Safe for signal handlers and atexit."""
        if not self._started:
            return

        self._stopping = True
        if self._process is not None:
            process, self._process = self._process, None
            self._end_process(process)

        if self._tunnel_info is not None:
            try:
                httpx.delete(
                    f"{self._client.base_url}/api/v1/tunnel/{self._tunnel_info.tunnel_id}",
                    headers=self._client._headers,
                    timeout=5.0,
                )
            except Exception:
                pass
            finally:
                self._tunnel_info = None

        if self._config_file is not None:
            try:
                if self._config_file.exists():
                    self._config_file.unlink()
            except Exception:
                pass
            finally:
                self._config_file = None

        self._started = False

    async def _cleanup(self) -> None:
        """Clean up tunnel resources."""
        # Stop frpc process (this will cause drain threads to exit via EOF)
        if self._process is not None:
            process, self._process = self._process, None
            self._end_process(process)

        # Delete tunnel registration
        if self._tunnel_info is not None:
            try:
                await self._client.delete_tunnel(self._tunnel_info.tunnel_id)
            except Exception:
                pass
            finally:
                self._tunnel_info = None

        # Clean up config file
        if self._config_file is not None:
            try:
                if self._config_file.exists():
                    self._config_file.unlink()
            except Exception:
                pass
            finally:
                self._config_file = None

        # Close HTTP client
        try:
            await self._client.close()
        except Exception:
            pass

    @property
    def recent_output(self) -> list[str]:
        """Last N lines of frpc output (thread-safe). Falls back to startup output."""
        if hasattr(self, "_output_lock"):
            if not self.is_running and hasattr(self, "_drain_threads"):
                for t in self._drain_threads:
                    t.join(timeout=2.0)
            with self._output_lock:
                return list(self._recent_output)
        return list(self._output_lines)

    def _start_pipe_drain(self, process: Optional[subprocess.Popen] = None) -> None:
        """Start background threads to drain subprocess pipes.

        Keeps the last 50 lines in a ring buffer for diagnostics (e.g. crash
        output) and forwards every line to the ``prime_tunnel.frpc`` logger,
        so reconnects and dropped control connections show up in the
        caller's logs. This also prevents the pipe buffer from filling up and
        blocking frpc when it produces output.
        """
        process = process or self._process
        if process is None:
            return

        # Each process gets its own lock and buffer, so a drain thread left
        # over from a replaced frpc cannot write into the new one's output.
        max_lines = 50
        lock = threading.Lock()
        recent: list[str] = list(self._output_lines[-max_lines:])
        self._output_lock = lock
        self._recent_output = recent
        tunnel_id = self.tunnel_id

        def drain_pipe(pipe):
            """Read output from a pipe, retaining recent lines."""
            if pipe is None:
                return
            try:
                for line in pipe:
                    line = line.rstrip("\n")
                    if line:
                        with lock:
                            recent.append(line)
                            if len(recent) > max_lines:
                                recent.pop(0)
                        _log_frpc_line(line, tunnel_id)
                        # A replaced frpc's leftover output says nothing about the new one.
                        if self._process is process and _reports_gone(line):
                            self._gone = True
            except (OSError, ValueError):
                pass  # Pipe closed

        self._drain_threads: list[threading.Thread] = []
        for pipe in (process.stdout, process.stderr):
            t = threading.Thread(target=drain_pipe, args=(pipe,), daemon=True)
            t.start()
            self._drain_threads.append(t)

    def _write_frpc_config(self) -> Path:
        """Generate and write frpc configuration file."""
        if self._tunnel_info is None:
            raise TunnelError("Tunnel not registered")

        server_host = self._tunnel_info.server_host
        server_port = self._tunnel_info.server_port

        # Generate config content
        config = f"""# Prime Tunnel frpc configuration
# Tunnel ID: {self._tunnel_info.tunnel_id}

serverAddr = "{server_host}"
serverPort = {server_port}

# Authentication
user = "{self._tunnel_info.tunnel_id}"
auth.method = "token"
auth.token = "{self._tunnel_info.frp_token}"

# Retry the initial login instead of exiting on the first transient failure
loginFailExit = false

# Per-tunnel binding secret
metadatas.binding_secret = "{self._tunnel_info.binding_secret}"

# Transport settings
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 30
transport.poolCount = 10
transport.dialServerKeepalive = 60

# Logging - always use console so we can detect connection via stdout
log.to = "console"
log.level = "{self.log_level}"

# HTTP proxy configuration
[[proxies]]
name = "{self._tunnel_info.tunnel_id}"
type = "http"
localIP = "{self.local_addr}"
localPort = {self.local_port}
subdomain = "{self._tunnel_info.tunnel_id}"
"""

        # Write to config directory
        config_dir = Path.home() / ".prime" / "tunnels"
        config_dir.mkdir(parents=True, exist_ok=True)
        config_dir.chmod(0o700)
        config_file = config_dir / f"{self._tunnel_info.tunnel_id}.toml"

        # Create file with 0600 permissions
        fd = os.open(str(config_file), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        try:
            os.write(fd, config.encode())
        finally:
            os.close(fd)

        return config_file

    async def _wait_for_connection(self, process: Optional[subprocess.Popen] = None) -> None:
        """Wait for frpc to establish connection."""
        start_time = time.time()
        self._output_lines = []

        while time.time() - start_time < self.connection_timeout:
            watched = process or self._process
            if watched is None:
                raise TunnelConnectionError(message="frpc process not running")

            return_code = watched.poll()
            if return_code is not None:
                remaining_output = []
                if watched.stdout:
                    remaining_output.extend(watched.stdout.readlines())
                if watched.stderr:
                    remaining_output.extend(watched.stderr.readlines())
                self._output_lines.extend(line.strip() for line in remaining_output if line.strip())

                raise _parse_frpc_error(self._output_lines, self.tunnel_id, return_code)

            if os.name == "posix":
                # Set both pipes to non-blocking mode to drain them without deadlock
                pipes_to_drain = []
                original_flags = {}

                for pipe in (watched.stdout, watched.stderr):
                    if pipe:
                        fd = pipe.fileno()
                        fl = fcntl.fcntl(fd, fcntl.F_GETFL)
                        original_flags[fd] = fl
                        fcntl.fcntl(fd, fcntl.F_SETFL, fl | os.O_NONBLOCK)
                        pipes_to_drain.append(pipe)

                try:
                    # Drain both stdout and stderr to prevent buffer exhaustion
                    for pipe in pipes_to_drain:
                        try:
                            while True:
                                line = pipe.readline()
                                if not line:
                                    break
                                line = line.strip()
                                if line:
                                    self._output_lines.append(line)
                                    verdict = _scan_startup_line(line)
                                    if verdict == "connected":
                                        return
                                    if verdict == "fatal":
                                        raise _parse_frpc_error(self._output_lines, self.tunnel_id)
                        except (BlockingIOError, IOError):
                            pass  # No more data available on this pipe
                finally:
                    # Restore original flags
                    for fd, fl in original_flags.items():
                        try:
                            fcntl.fcntl(fd, fcntl.F_SETFL, fl)
                        except (OSError, ValueError):
                            pass  # Pipe may have closed

            await asyncio.sleep(0.1)

        # Timeout - include any captured output
        output_text = (
            "\n".join(self._output_lines) if self._output_lines else "(no output captured)"
        )
        raise TunnelTimeoutError(
            f"Tunnel connection timed out after {self.connection_timeout}s\n"
            f"--- frpc output ---\n{output_text}\n-------------------"
        )

    async def __aenter__(self) -> "Tunnel":
        """Async context manager entry."""
        await self.start()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.stop()
