import asyncio
import os
import subprocess
import time
from pathlib import Path
from typing import Optional

import httpx

from prime_tunnel.binary import get_frpc_path
from prime_tunnel.core.client import TunnelClient
from prime_tunnel.exceptions import (
    TunnelConnectionError,
    TunnelError,
    TunnelGoneError,
    TunnelTimeoutError,
)
from prime_tunnel.frpc import FrpcEvent, FrpcOutput, failure_message
from prime_tunnel.models import TunnelInfo, TunnelStatus

# Statuses the tunnel service never leaves.
_TERMINAL_STATUSES = ("expired", "terminated")


class Tunnel:
    """Tunnel interface for exposing local services."""

    def __init__(
        self,
        local_port: int,
        local_addr: str = "127.0.0.1",
        name: Optional[str] = None,
        connection_timeout: float = 30.0,
        log_level: str = "info",
        team_id: Optional[str] = None,
        labels: Optional[list[str]] = None,
        http_user: Optional[str] = None,
    ):
        """
        Initialize a tunnel.

        Args:
            local_port: Local port to tunnel
            local_addr: Local address to tunnel (default: 127.0.0.1)
            name: Optional friendly name for the tunnel
            team_id: Optional team ID for team tunnels
            labels: Optional labels for organizing tunnels
            connection_timeout: Timeout for establishing connection (seconds)
            log_level: frpc log level (trace, debug, info, warn, error)
            http_user: Optional HTTP basic auth username protecting tunnel
                traffic. The password is auto-generated by the backend;
                read it from the http_password property after start().
        """
        self.local_port = local_port
        self.local_addr = local_addr
        self.name = name
        self.team_id = team_id
        self.labels = labels or []
        self.connection_timeout = connection_timeout
        self.log_level = log_level
        self.http_user = http_user

        self._client = TunnelClient()
        self._process: Optional[subprocess.Popen] = None
        self._tunnel_info: Optional[TunnelInfo] = None
        self._config_file: Optional[Path] = None
        self._started = False
        self._stopping = False
        self._gone = False
        # Serializes start() and restart().
        self._process_lock = asyncio.Lock()
        # Output of the frpc launched last, kept after it exits.
        self._output: Optional[FrpcOutput] = None

    @property
    def tunnel_id(self) -> Optional[str]:
        """Get the tunnel ID."""
        return self._tunnel_info.tunnel_id if self._tunnel_info else None

    @property
    def url(self) -> Optional[str]:
        """Get the tunnel URL."""
        return self._tunnel_info.url if self._tunnel_info else None

    @property
    def hostname(self) -> Optional[str]:
        """Get the tunnel hostname."""
        return self._tunnel_info.hostname if self._tunnel_info else None

    @property
    def http_password(self) -> Optional[str]:
        """Get the auto-generated basic auth password (set after start()).

        Only available on the Tunnel instance that created the registration;
        it cannot be retrieved again later.
        """
        return self._tunnel_info.http_password if self._tunnel_info else None

    @property
    def is_running(self) -> bool:
        """Check if the tunnel is running."""
        if self._process is None:
            return False
        return self._process.poll() is None

    @property
    def is_gone(self) -> bool:
        """Whether the registration is known to be unusable. Makes no API call.

        Set when the tunnel service rejects frpc because the tunnel was
        deleted, expired, or stayed disconnected for too long, or when
        status() finds the same. restart() cannot bring such a tunnel back:
        stop it and start a new one.
        """
        return self._gone

    async def check_registered(self) -> bool:
        """Check if the tunnel's registration can still be used.

        Calls get_tunnel() on the backend API. Returns False if the service
        has no record of the tunnel or reports it expired or terminated.

        Raises TunnelError/TunnelTimeoutError on transient API failures
        so the caller can distinguish "tunnel gone" from "API unreachable".
        """
        if self._tunnel_info is None:
            return False
        info = await self._client.get_tunnel(self._tunnel_info.tunnel_id)
        return info is not None and (info.status or "").lower() not in _TERMINAL_STATUSES

    async def status(self) -> TunnelStatus:
        """
        Report the local frpc process and the tunnel service's record.

        A registration the service reports as connected is not proof that
        the URL is serving; disconnected, expired and terminated are reliable.

        Returns:
            TunnelStatus for this tunnel

        Raises:
            TunnelError: If the tunnel is not started or the API call fails
            TunnelTimeoutError: If the API call times out
        """
        if self._tunnel_info is None:
            raise TunnelError("Tunnel is not started")
        tunnel_id = self._tunnel_info.tunnel_id
        info = await self._client.get_tunnel(tunnel_id)
        registration = None
        if info is not None and info.status:
            registration = info.status.lower()
        if info is None or registration in _TERMINAL_STATUSES:
            self._gone = True
        return TunnelStatus(
            tunnel_id=tunnel_id,
            running=self.is_running,
            registration=registration,
            gone=self._gone,
        )

    async def start(self) -> str:
        """
        Start the tunnel.

        Returns:
            The tunnel URL

        Raises:
            TunnelError: If tunnel registration fails
            TunnelConnectionError: If frpc fails to connect or tunnel is not running
            TunnelTimeoutError: If connection times out
        """
        if self._started:
            raise TunnelError("Tunnel is already started")

        async with self._process_lock:
            if self._started:
                raise TunnelError("Tunnel is already started")
            self._stopping = False
            return await self._register_and_connect()

    async def _register_and_connect(self) -> str:
        """Register the tunnel, start frpc and wait for it to connect."""
        self._gone = False
        # 1. Get frpc binary
        frpc_path = await asyncio.to_thread(get_frpc_path)

        # 2. Register tunnel with backend
        try:
            self._tunnel_info = await self._client.create_tunnel(
                local_port=self.local_port,
                name=self.name,
                team_id=self.team_id,
                labels=self.labels,
                http_user=self.http_user,
            )
        except BaseException as e:
            await self._cleanup()
            if isinstance(e, (asyncio.CancelledError, TunnelError)):
                raise
            raise TunnelError(f"Failed to register tunnel: {e}") from e

        # 3. Generate frpc config
        try:
            self._config_file = self._write_frpc_config()
        except BaseException as e:
            await self._cleanup()
            if isinstance(e, asyncio.CancelledError):
                raise
            raise TunnelError(f"Failed to write frpc config: {e}") from e

        # 4. Start frpc process and read its output
        try:
            self._process = subprocess.Popen(
                [str(frpc_path), "-c", str(self._config_file)],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            self._start_output_reader(self._process)
        except BaseException as e:
            await self._cleanup()
            if isinstance(e, asyncio.CancelledError):
                raise
            raise TunnelConnectionError(message=f"Failed to start frpc: {e}") from e

        # 5. Wait for connection
        try:
            await self._wait_for_connection()
        except BaseException:
            await self._cleanup()
            raise

        self._started = True

        return self.url

    async def restart(self) -> str:
        """
        Restart frpc, keeping the tunnel's registration and URL.

        If the restart fails, the tunnel stays registered with no frpc
        running: call restart() again or stop(). A tunnel that was deleted,
        expired, or stayed disconnected for too long cannot be restarted.

        Returns:
            The tunnel URL

        Raises:
            TunnelError: If the tunnel is not started or is stopped meanwhile
            TunnelGoneError: If the registration can no longer be used
            TunnelConnectionError: If frpc fails to start or connect
            TunnelTimeoutError: If connection times out
        """
        if not self._started or self._stopping:
            raise TunnelError("Tunnel is not started")

        async with self._process_lock:
            if not self._started or self._stopping:
                raise TunnelError("Tunnel is not started")

            url = self.url
            frpc_path = await asyncio.to_thread(get_frpc_path)

            old_process, self._process = self._process, None
            if old_process is not None:
                await asyncio.to_thread(self._end_process, old_process, kill=True)

            if self._stopping:
                raise TunnelError("Tunnel was stopped during restart")

            try:
                process = subprocess.Popen(
                    [str(frpc_path), "-c", str(self._config_file)],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                )
            except Exception as e:
                raise TunnelConnectionError(message=f"Failed to start frpc: {e}") from e
            self._process = process

            stopped = TunnelError("Tunnel was stopped during restart")
            was_gone = self._gone
            try:
                # A stop during launch saw no process to end.
                if self._stopping:
                    raise stopped
                # Cleared before the new frpc can report, so that a rejection
                # arriving right after it connects is not wiped out.
                self._gone = False
                self._start_output_reader(process)
                await self._wait_for_connection(process)
                if self._stopping:
                    raise stopped
            except BaseException as e:
                # A restart that failed for another reason proves nothing.
                self._gone = self._gone or was_gone
                await asyncio.to_thread(self._end_process, process, kill=True)
                if not self._stopping or not isinstance(e, Exception):
                    raise
                self._process = None
                if e is stopped:
                    raise
                raise stopped from e

            return url

    @staticmethod
    def _end_process(process: subprocess.Popen, kill: bool = False) -> None:
        """Terminate frpc, or kill it at once if `kill` is set."""
        try:
            if kill:
                process.kill()
                process.wait(timeout=2)
                return
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=2)
        except Exception:
            pass

    async def stop(self) -> None:
        """Stop the tunnel and cleanup resources."""
        if not self._started:
            return

        self._stopping = True
        await self._cleanup()
        self._started = False

    def sync_stop(self) -> None:
        """Stop the tunnel synchronously. Safe for signal handlers and atexit."""
        if not self._started:
            return

        self._stopping = True
        if self._process is not None:
            process, self._process = self._process, None
            self._end_process(process)

        if self._tunnel_info is not None:
            try:
                httpx.delete(
                    f"{self._client.base_url}/api/v1/tunnel/{self._tunnel_info.tunnel_id}",
                    headers=self._client._headers,
                    timeout=5.0,
                )
            except Exception:
                pass
            finally:
                self._tunnel_info = None

        if self._config_file is not None:
            try:
                if self._config_file.exists():
                    self._config_file.unlink()
            except Exception:
                pass
            finally:
                self._config_file = None

        self._started = False

    async def _cleanup(self) -> None:
        """Clean up tunnel resources."""
        # Stop frpc process (this will cause drain threads to exit via EOF)
        if self._process is not None:
            process, self._process = self._process, None
            self._end_process(process)

        # Delete tunnel registration
        if self._tunnel_info is not None:
            try:
                await self._client.delete_tunnel(self._tunnel_info.tunnel_id)
            except Exception:
                pass
            finally:
                self._tunnel_info = None

        # Clean up config file
        if self._config_file is not None:
            try:
                if self._config_file.exists():
                    self._config_file.unlink()
            except Exception:
                pass
            finally:
                self._config_file = None

        # Close HTTP client
        try:
            await self._client.close()
        except Exception:
            pass

    @property
    def recent_output(self) -> list[str]:
        """Last lines of output from the frpc launched last (thread-safe)."""
        output = self._output
        if output is None:
            return []
        if not self.is_running:
            output.join()
        return output.lines()

    def _start_output_reader(self, process: subprocess.Popen) -> None:
        """Read the output of a just-launched frpc in the background."""

        def on_event(event: FrpcEvent) -> None:
            # A replaced frpc's leftover output says nothing about the new one.
            if event is FrpcEvent.GONE and self._process is process:
                self._gone = True

        self._output = FrpcOutput(process, self.tunnel_id, on_event=on_event)

    def _write_frpc_config(self) -> Path:
        """Generate and write frpc configuration file."""
        if self._tunnel_info is None:
            raise TunnelError("Tunnel not registered")

        server_host = self._tunnel_info.server_host
        server_port = self._tunnel_info.server_port

        # Generate config content
        config = f"""# Prime Tunnel frpc configuration
# Tunnel ID: {self._tunnel_info.tunnel_id}

serverAddr = "{server_host}"
serverPort = {server_port}

# Authentication
user = "{self._tunnel_info.tunnel_id}"
auth.method = "token"
auth.token = "{self._tunnel_info.frp_token}"

# Retry the initial login instead of exiting on the first transient failure
loginFailExit = false

# Per-tunnel binding secret
metadatas.binding_secret = "{self._tunnel_info.binding_secret}"

# Transport settings
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 30
transport.poolCount = 10
transport.dialServerKeepalive = 60

# Logging - always use console so we can detect connection via stdout
log.to = "console"
log.level = "{self.log_level}"

# HTTP proxy configuration
[[proxies]]
name = "{self._tunnel_info.tunnel_id}"
type = "http"
localIP = "{self.local_addr}"
localPort = {self.local_port}
subdomain = "{self._tunnel_info.tunnel_id}"
"""

        # Write to config directory
        config_dir = Path.home() / ".prime" / "tunnels"
        config_dir.mkdir(parents=True, exist_ok=True)
        config_dir.chmod(0o700)
        config_file = config_dir / f"{self._tunnel_info.tunnel_id}.toml"

        # Create file with 0600 permissions
        fd = os.open(str(config_file), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        try:
            os.write(fd, config.encode())
        finally:
            os.close(fd)

        return config_file

    async def _wait_for_connection(self, process: Optional[subprocess.Popen] = None) -> None:
        """Wait for frpc to establish connection."""
        process = process or self._process
        output = self._output
        if process is None or output is None:
            raise TunnelConnectionError(message="frpc process not running")

        deadline = time.monotonic() + self.connection_timeout
        while time.monotonic() < deadline:
            return_code = process.poll()
            if return_code is not None:
                output.join()
                raise self._frpc_error(output, return_code)

            event = output.first_event
            if event is FrpcEvent.CONNECTED:
                return
            # Anything else frpc reports is a failure it will not get past
            # soon enough: it retries a refused proxy only after 30s.
            if event is not None:
                raise self._frpc_error(output)

            await asyncio.sleep(0.1)

        output_text = "\n".join(output.lines()) or "(no output captured)"
        raise TunnelTimeoutError(
            f"Tunnel connection timed out after {self.connection_timeout}s\n"
            f"--- frpc output ---\n{output_text}\n-------------------"
        )

    def _frpc_error(
        self, output: FrpcOutput, return_code: Optional[int] = None
    ) -> TunnelConnectionError:
        """Build the exception for an frpc that failed to connect."""
        message = failure_message(output.lines(), return_code)
        if output.first_event is FrpcEvent.GONE:
            return TunnelGoneError(tunnel_id=self.tunnel_id, message=message)
        return TunnelConnectionError(tunnel_id=self.tunnel_id, message=message)

    async def __aenter__(self) -> "Tunnel":
        """Async context manager entry."""
        await self.start()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.stop()
