"""Declarative Prime CLI command registry."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Command:
    path: tuple[str, ...]
    callback: str
    summary: str
    section: str
    config: str | None = None
    positionals: tuple[str, ...] = ()
    raw: bool = False


GROUPS: dict[tuple[str, ...], str] = {
    ("availability",): "Check GPU availability and pricing.",
    ("config",): "Configure the Prime CLI.",
    ("deployments",): "Manage adapter deployments.",
    ("disks",): "Manage persistent storage.",
    ("env",): "Manage Verifiers environments and Hub publishing.",
    ("env", "action"): "Manage environment actions.",
    ("env", "secret"): "Manage environment secrets.",
    ("env", "var"): "Manage environment variables.",
    ("env", "version"): "Manage environment versions.",
    ("eval",): "Run local evaluations or manage hosted evaluations.",
    ("gepa",): "Run GEPA prompt optimization with Verifiers.",
    ("images",): "Manage container images in the Prime registry.",
    ("inference",): "Use Prime Inference.",
    ("lab",): "Manage the Prime Lab workspace.",
    ("pods",): "Manage compute pods.",
    ("registry",): "Manage registry credentials and private images.",
    ("sandbox",): "Manage sandboxes.",
    ("secret",): "Manage global secrets.",
    ("teams",): "Inspect teams and memberships.",
    ("train",): "Launch and manage Hosted Training runs.",
    ("tunnel",): "Manage tunnels for exposing local services.",
}


COMMANDS: tuple[Command, ...] = (
    Command(
        path=("availability", "disks"),
        callback="prime_cli.commands.availability:disks",
        summary="List available disks",
        section="Compute",
        config="prime_cli.command_configs:AvailabilityDisksConfig",
    ),
    Command(
        path=("availability", "gpu-types"),
        callback="prime_cli.commands.availability:gpu_types",
        summary="List available GPU types",
        section="Compute",
        config="prime_cli.command_configs:AvailabilityGpuTypesConfig",
    ),
    Command(
        path=("availability", "list"),
        callback="prime_cli.commands.availability:list",
        summary="List available GPU resources",
        section="Compute",
        config="prime_cli.command_configs:AvailabilityListConfig",
    ),
    Command(
        path=("config", "delete"),
        callback="prime_cli.commands.config:delete_env",
        summary="Delete a saved environment",
        section="Account",
        config="prime_cli.command_configs:ConfigDeleteConfig",
        positionals=("name",),
    ),
    Command(
        path=("config", "envs"),
        callback="prime_cli.commands.config:list_envs",
        summary="List available environments",
        section="Account",
        config="prime_cli.command_configs:ConfigEnvsConfig",
    ),
    Command(
        path=("config", "remove-team-id"),
        callback="prime_cli.commands.config:remove_team_id",
        summary="Remove team ID to use personal account",
        section="Account",
        config="prime_cli.command_configs:ConfigRemoveTeamIdConfig",
    ),
    Command(
        path=("config", "reset"),
        callback="prime_cli.commands.config:reset",
        summary="Reset configuration to defaults",
        section="Account",
        config="prime_cli.command_configs:ConfigResetConfig",
    ),
    Command(
        path=("config", "save"),
        callback="prime_cli.commands.config:save_env",
        summary="Save current config as environment (including API key)",
        section="Account",
        config="prime_cli.command_configs:ConfigSaveConfig",
        positionals=("name",),
    ),
    Command(
        path=("config", "set-api-key"),
        callback="prime_cli.commands.config:set_api_key",
        summary="Set your API key (prompts securely if not provided)",
        section="Account",
        config="prime_cli.command_configs:ConfigSetApiKeyConfig",
        positionals=("api_key",),
    ),
    Command(
        path=("config", "set-base-url"),
        callback="prime_cli.commands.config:set_base_url",
        summary="Set the API base URL (prompts if not provided)",
        section="Account",
        config="prime_cli.command_configs:ConfigSetBaseUrlConfig",
        positionals=("url",),
    ),
    Command(
        path=("config", "set-frontend-url"),
        callback="prime_cli.commands.config:set_frontend_url",
        summary="Set the frontend URL (prompts if not provided)",
        section="Account",
        config="prime_cli.command_configs:ConfigSetFrontendUrlConfig",
        positionals=("url",),
    ),
    Command(
        path=("config", "set-inference-url"),
        callback="prime_cli.commands.config:set_inference_url",
        summary="Set the inference URL (prompts if not provided)",
        section="Account",
        config="prime_cli.command_configs:ConfigSetInferenceUrlConfig",
        positionals=("url",),
    ),
    Command(
        path=("config", "set-share-resources-with-team"),
        callback="prime_cli.commands.config:set_share_resources_with_team",
        summary="Set whether to automatically share new resources with all team members",
        section="Account",
        config="prime_cli.command_configs:ConfigSetShareResourcesWithTeamConfig",
        positionals=("enabled",),
    ),
    Command(
        path=("config", "set-ssh-key-path"),
        callback="prime_cli.commands.config:set_ssh_key_path",
        summary="Set the SSH private key path",
        section="Account",
        config="prime_cli.command_configs:ConfigSetSshKeyPathConfig",
        positionals=("path",),
    ),
    Command(
        path=("config", "set-team-id"),
        callback="prime_cli.commands.config:set_team_id",
        summary="Set your team ID.",
        section="Account",
        config="prime_cli.command_configs:ConfigSetTeamIdConfig",
        positionals=("team_id",),
    ),
    Command(
        path=("config", "use"),
        callback="prime_cli.commands.config:use_environment",
        summary="Switch to a different environment",
        section="Account",
        config="prime_cli.command_configs:ConfigUseConfig",
        positionals=("env",),
    ),
    Command(
        path=("config", "view"),
        callback="prime_cli.commands.config:view",
        summary="View current configuration",
        section="Account",
        config="prime_cli.command_configs:ConfigViewConfig",
    ),
    Command(
        path=("deployments", "create"),
        callback="prime_cli.commands.deployments:create_deployment",
        summary="Deploy a model for inference.",
        section="Lab",
        config="prime_cli.command_configs:DeploymentsCreateConfig",
        positionals=("model_id",),
    ),
    Command(
        path=("deployments", "delete"),
        callback="prime_cli.commands.deployments:delete_deployment",
        summary="Unload a model from inference.",
        section="Lab",
        config="prime_cli.command_configs:DeploymentsDeleteConfig",
        positionals=("model_id",),
    ),
    Command(
        path=("deployments", "list"),
        callback="prime_cli.commands.deployments:list_deployments",
        summary="List adapters and their deployment status.",
        section="Lab",
        config="prime_cli.command_configs:DeploymentsListConfig",
    ),
    Command(
        path=("disks", "create"),
        callback="prime_cli.commands.disks:create",
        summary="Create a new storage disk",
        section="Compute",
        config="prime_cli.command_configs:DisksCreateConfig",
    ),
    Command(
        path=("disks", "get"),
        callback="prime_cli.commands.disks:get",
        summary="Get detailed information about a specific disk",
        section="Compute",
        config="prime_cli.command_configs:DisksGetConfig",
        positionals=("disk_id",),
    ),
    Command(
        path=("disks", "list"),
        callback="prime_cli.commands.disks:list",
        summary="List your persistent disks",
        section="Compute",
        config="prime_cli.command_configs:DisksListConfig",
    ),
    Command(
        path=("disks", "terminate"),
        callback="prime_cli.commands.disks:terminate",
        summary="Terminate a disk",
        section="Compute",
        config="prime_cli.command_configs:DisksTerminateConfig",
        positionals=("disk_id",),
    ),
    Command(
        path=("disks", "update"),
        callback="prime_cli.commands.disks:update",
        summary="Update a disk's name",
        section="Compute",
        config="prime_cli.command_configs:DisksUpdateConfig",
        positionals=("disk_id",),
    ),
    Command(
        path=("env", "action", "list"),
        callback="prime_cli.commands.env:actions_list",
        summary="List actions (CI jobs) for an environment.",
        section="Lab",
        config="prime_cli.command_configs:EnvActionListConfig",
        positionals=("environment",),
    ),
    Command(
        path=("env", "action", "logs"),
        callback="prime_cli.commands.env:actions_logs",
        summary="Get logs for a specific action.",
        section="Lab",
        config="prime_cli.command_configs:EnvActionLogsConfig",
        positionals=("environment", "action_id"),
    ),
    Command(
        path=("env", "action", "retry"),
        callback="prime_cli.commands.env:actions_retry",
        summary="Retry an action (integration test) for an environment.",
        section="Lab",
        config="prime_cli.command_configs:EnvActionRetryConfig",
        positionals=("environment", "action_id"),
    ),
    Command(
        path=("env", "build"),
        callback="prime_cli.commands.env:build",
        summary="Build an OpenEnv-backed environment image.",
        section="Lab",
        config="prime_cli.command_configs:EnvBuildConfig",
        positionals=("env_id",),
    ),
    Command(
        path=("env", "delete"),
        callback="prime_cli.commands.env:delete",
        summary="Delete an entire environment from the environments hub",
        section="Lab",
        config="prime_cli.command_configs:EnvDeleteConfig",
        positionals=("env_id",),
    ),
    Command(
        path=("env", "info"),
        callback="prime_cli.commands.env:info",
        summary="Show environment details and installation commands",
        section="Lab",
        config="prime_cli.command_configs:EnvInfoConfig",
        positionals=("env_id",),
    ),
    Command(
        path=("env", "init"),
        callback="prime_cli.commands.env:init",
        summary="Initialize a V1 or V0 environment with Verifiers.",
        section="Lab",
        raw=True,
    ),
    Command(
        path=("env", "inspect"),
        callback="prime_cli.commands.env:inspect_cmd",
        summary="Inspect environment source without downloading the archive locally.",
        section="Lab",
        config="prime_cli.command_configs:EnvInspectConfig",
        positionals=("env_id", "source_path"),
    ),
    Command(
        path=("env", "install"),
        callback="prime_cli.commands.env:install",
        summary="Install a verifiers environment.",
        section="Lab",
        config="prime_cli.command_configs:EnvInstallConfig",
        positionals=("env_ids",),
    ),
    Command(
        path=("env", "list"),
        callback="prime_cli.commands.env:list_cmd",
        summary="List environments from the hub.",
        section="Lab",
        config="prime_cli.command_configs:EnvListConfig",
    ),
    Command(
        path=("env", "pull"),
        callback="prime_cli.commands.env:pull",
        summary="Pull environment for local inspection",
        section="Lab",
        config="prime_cli.command_configs:EnvPullConfig",
        positionals=("env_id",),
    ),
    Command(
        path=("env", "push"),
        callback="prime_cli.commands.env:push",
        summary="Push environment to registry",
        section="Lab",
        config="prime_cli.command_configs:EnvPushConfig",
        positionals=("env_id",),
    ),
    Command(
        path=("env", "secret", "create"),
        callback="prime_cli.commands.env:env_secret_create",
        summary="Create an environment-specific secret.",
        section="Lab",
        config="prime_cli.command_configs:EnvSecretCreateConfig",
        positionals=("environment",),
    ),
    Command(
        path=("env", "secret", "delete"),
        callback="prime_cli.commands.env:env_secret_delete",
        summary="Delete an environment-specific secret.",
        section="Lab",
        config="prime_cli.command_configs:EnvSecretDeleteConfig",
        positionals=("environment",),
    ),
    Command(
        path=("env", "secret", "link"),
        callback="prime_cli.commands.env:env_secret_link",
        summary="Link a global secret to an environment.",
        section="Lab",
        config="prime_cli.command_configs:EnvSecretLinkConfig",
        positionals=("global_secret_id", "environment"),
    ),
    Command(
        path=("env", "secret", "list"),
        callback="prime_cli.commands.env:env_secret_list",
        summary="List all secrets for an environment.",
        section="Lab",
        config="prime_cli.command_configs:EnvSecretListConfig",
        positionals=("environment",),
    ),
    Command(
        path=("env", "secret", "unlink"),
        callback="prime_cli.commands.env:env_secret_unlink",
        summary="Unlink a global secret from an environment.",
        section="Lab",
        config="prime_cli.command_configs:EnvSecretUnlinkConfig",
        positionals=("global_secret_id", "environment"),
    ),
    Command(
        path=("env", "secret", "update"),
        callback="prime_cli.commands.env:env_secret_update",
        summary="Update an environment-specific secret.",
        section="Lab",
        config="prime_cli.command_configs:EnvSecretUpdateConfig",
        positionals=("environment",),
    ),
    Command(
        path=("env", "serve"),
        callback="prime_cli.commands.env:serve",
        summary="Serve a V1 or V0 environment with Verifiers.",
        section="Lab",
        raw=True,
    ),
    Command(
        path=("env", "status"),
        callback="prime_cli.commands.env:status_cmd",
        summary="Show action status for an environment.",
        section="Lab",
        config="prime_cli.command_configs:EnvStatusConfig",
        positionals=("env_id",),
    ),
    Command(
        path=("env", "uninstall"),
        callback="prime_cli.commands.env:uninstall",
        summary="Uninstall an environment distribution with uv.",
        section="Lab",
        config="prime_cli.command_configs:EnvUninstallConfig",
        positionals=("env_name",),
    ),
    Command(
        path=("env", "validate"),
        callback="prime_cli.commands.env:validate",
        summary="Run a taskset's model-free validation with Verifiers.",
        section="Lab",
        raw=True,
    ),
    Command(
        path=("env", "var", "create"),
        callback="prime_cli.commands.env:var_create",
        summary="Create an environment variable.",
        section="Lab",
        config="prime_cli.command_configs:EnvVarCreateConfig",
        positionals=("environment",),
    ),
    Command(
        path=("env", "var", "delete"),
        callback="prime_cli.commands.env:var_delete",
        summary="Delete an environment variable.",
        section="Lab",
        config="prime_cli.command_configs:EnvVarDeleteConfig",
        positionals=("var_id", "environment"),
    ),
    Command(
        path=("env", "var", "list"),
        callback="prime_cli.commands.env:var_list",
        summary="List all variables for an environment.",
        section="Lab",
        config="prime_cli.command_configs:EnvVarListConfig",
        positionals=("environment",),
    ),
    Command(
        path=("env", "var", "update"),
        callback="prime_cli.commands.env:var_update",
        summary="Update an environment variable.",
        section="Lab",
        config="prime_cli.command_configs:EnvVarUpdateConfig",
        positionals=("var_id", "environment"),
    ),
    Command(
        path=("env", "version", "delete"),
        callback="prime_cli.commands.env:delete_version",
        summary="Delete an environment version by content hash",
        section="Lab",
        config="prime_cli.command_configs:EnvVersionDeleteConfig",
        positionals=("env_id", "content_hash"),
    ),
    Command(
        path=("env", "version", "list"),
        callback="prime_cli.commands.env:list_versions",
        summary="List all versions of an environment",
        section="Lab",
        config="prime_cli.command_configs:EnvVersionListConfig",
        positionals=("env_id",),
    ),
    Command(
        path=("eval", "get"),
        callback="prime_cli.commands.evals:get_eval",
        summary="Show evaluation details.",
        section="Lab",
        config="prime_cli.command_configs:EvalGetConfig",
        positionals=("eval_id",),
    ),
    Command(
        path=("eval", "list"),
        callback="prime_cli.commands.evals:list_evals",
        summary="List evaluations.",
        section="Lab",
        config="prime_cli.command_configs:EvalListConfig",
    ),
    Command(
        path=("eval", "logs"),
        callback="prime_cli.commands.evals:logs_cmd",
        summary="Get logs for a hosted evaluation.",
        section="Lab",
        config="prime_cli.command_configs:EvalLogsConfig",
        positionals=("eval_id",),
    ),
    Command(
        path=("eval", "push"),
        callback="prime_cli.commands.evals:push_eval",
        summary="Push native or legacy evaluation data to Prime Evals.",
        section="Lab",
        config="prime_cli.command_configs:EvalPushConfig",
        positionals=("config_path",),
    ),
    Command(
        path=("eval", "run"),
        callback="prime_cli.commands.evals:run_eval_cmd",
        summary="Run a local V1 or V0 evaluation with Verifiers",
        section="Lab",
        raw=True,
    ),
    Command(
        path=("eval", "samples"),
        callback="prime_cli.commands.evals:get_samples",
        summary="",
        section="Lab",
        config="prime_cli.command_configs:EvalSamplesConfig",
        positionals=("eval_id",),
    ),
    Command(
        path=("eval", "stop"),
        callback="prime_cli.commands.evals:stop_cmd",
        summary="Stop a running hosted evaluation.",
        section="Lab",
        config="prime_cli.command_configs:EvalStopConfig",
        positionals=("eval_id",),
    ),
    Command(
        path=("eval", "submit"),
        callback="prime_cli.commands.evals:submit_eval_cmd",
        summary="Submit a hosted V0 evaluation",
        section="Lab",
        config="prime_cli.command_configs:EvalSubmitConfig",
        positionals=("environment",),
    ),
    Command(
        path=("eval", "view"),
        callback="prime_cli.commands.evals:view_cmd",
        summary="Launch the interactive evaluation viewer.",
        section="Lab",
        config="prime_cli.command_configs:EvalViewConfig",
    ),
    Command(
        path=("feedback",),
        callback="prime_cli.commands.feedback:feedback",
        summary="Submit feedback about Prime Intellect.",
        section="Account",
        config="prime_cli.command_configs:FeedbackConfig",
    ),
    Command(
        path=("fork",),
        callback="prime_cli.commands.fork:fork",
        summary="Fork a public environment into your Prime Intellect namespace.",
        section="Lab",
        config="prime_cli.command_configs:ForkConfig",
        positionals=("environment",),
    ),
    Command(
        path=("gepa", "run"),
        callback="prime_cli.commands.gepa:run_gepa_cmd",
        summary="Run Verifiers' native GEPA command.",
        section="Lab",
        raw=True,
    ),
    Command(
        path=("images", "delete"),
        callback="prime_cli.commands.images:delete_image",
        summary="Delete an image from your registry.",
        section="Compute",
        config="prime_cli.command_configs:ImagesDeleteConfig",
        positionals=("image_reference",),
    ),
    Command(
        path=("images", "list"),
        callback="prime_cli.commands.images:list_images",
        summary="List all images you've pushed to Prime Intellect registry.",
        section="Compute",
        config="prime_cli.command_configs:ImagesListConfig",
    ),
    Command(
        path=("images", "publish"),
        callback="prime_cli.commands.images:publish_image",
        summary="Make an image public so other Prime users can run it.",
        section="Compute",
        config="prime_cli.command_configs:ImagesPublishConfig",
        positionals=("image_reference",),
    ),
    Command(
        path=("images", "push"),
        callback="prime_cli.commands.images:push_image",
        summary="Build and push a Docker image to Prime Intellect registry.",
        section="Compute",
        config="prime_cli.command_configs:ImagesPushConfig",
        positionals=("image_reference",),
    ),
    Command(
        path=("images", "unpublish"),
        callback="prime_cli.commands.images:unpublish_image",
        summary="Make a public image private again.",
        section="Compute",
        config="prime_cli.command_configs:ImagesUnpublishConfig",
        positionals=("image_reference",),
    ),
    Command(
        path=("inference", "chat"),
        callback="prime_cli.commands.inference:chat",
        summary="Send a one-shot chat message to a Prime Inference model.",
        section="Compute",
        config="prime_cli.command_configs:InferenceChatConfig",
        positionals=("model", "message"),
    ),
    Command(
        path=("inference", "models"),
        callback="prime_cli.commands.inference:list_models",
        summary="List available models from Prime Inference (/v1/models).",
        section="Compute",
        config="prime_cli.command_configs:InferenceModelsConfig",
    ),
    Command(
        path=("lab", "doctor"),
        callback="prime_cli.commands.lab:doctor",
        summary="Check a Lab workspace.",
        section="Lab",
        config="prime_cli.command_configs:LabDoctorConfig",
    ),
    Command(
        path=("lab", "hygiene"),
        callback="prime_cli.commands.lab:hygiene",
        summary="Check cheap Lab git hygiene.",
        section="Lab",
        config="prime_cli.command_configs:LabHygieneConfig",
    ),
    Command(
        path=("lab", "mcp"),
        callback="prime_cli.commands.lab:mcp",
        summary="Run the Lab MCP server over stdio.",
        section="Lab",
        config="prime_cli.command_configs:LabMcpConfig",
    ),
    Command(
        path=("lab", "register-github"),
        callback="prime_cli.commands.lab:register_github",
        summary="Write the GitHub workflow for Lab git hygiene.",
        section="Lab",
        config="prime_cli.command_configs:LabRegisterGithubConfig",
    ),
    Command(
        path=("lab", "setup"),
        callback="prime_cli.commands.lab:setup",
        summary="Set up a Lab workspace.",
        section="Lab",
        config="prime_cli.command_configs:LabSetupConfig",
    ),
    Command(
        path=("lab", "sync"),
        callback="prime_cli.commands.lab:sync",
        summary="Refresh Lab skills and local agent guidance.",
        section="Lab",
        config="prime_cli.command_configs:LabSyncConfig",
    ),
    Command(
        path=("lab", "view"),
        callback="prime_cli.commands.lab:_launch_view",
        summary="Launch the interactive Lab viewer.",
        section="Lab",
        config="prime_cli.command_configs:LabViewConfig",
    ),
    Command(
        path=("login",),
        callback="prime_cli.commands.login:login",
        summary="Login to Prime Intellect",
        section="Account",
        config="prime_cli.command_configs:LoginConfig",
    ),
    Command(
        path=("logout",),
        callback="prime_cli.commands.logout:logout",
        summary="Log out of Prime Intellect",
        section="Account",
        config="prime_cli.command_configs:LogoutConfig",
    ),
    Command(
        path=("pods", "create"),
        callback="prime_cli.commands.pods:create",
        summary="Create a new pod with an interactive setup process",
        section="Compute",
        config="prime_cli.command_configs:PodsCreateConfig",
    ),
    Command(
        path=("pods", "history"),
        callback="prime_cli.commands.pods:history",
        summary="List your pods history (terminated pods)",
        section="Compute",
        config="prime_cli.command_configs:PodsHistoryConfig",
    ),
    Command(
        path=("pods", "list"),
        callback="prime_cli.commands.pods:list",
        summary="List your running pods",
        section="Compute",
        config="prime_cli.command_configs:PodsListConfig",
    ),
    Command(
        path=("pods", "ssh"),
        callback="prime_cli.commands.pods:connect",
        summary="SSH / connect to a pod using configured SSH key",
        section="Compute",
        config="prime_cli.command_configs:PodsSshConfig",
        positionals=("pod_id",),
    ),
    Command(
        path=("pods", "status"),
        callback="prime_cli.commands.pods:status",
        summary="Get detailed status of a specific pod",
        section="Compute",
        config="prime_cli.command_configs:PodsStatusConfig",
        positionals=("pod_id",),
    ),
    Command(
        path=("pods", "terminate"),
        callback="prime_cli.commands.pods:terminate",
        summary="Terminate a pod",
        section="Compute",
        config="prime_cli.command_configs:PodsTerminateConfig",
        positionals=("pod_id",),
    ),
    Command(
        path=("registry", "check-image"),
        callback="prime_cli.commands.registry:check_docker_image",
        summary="Verify that an image is accessible (optionally using registry credentials).",
        section="Compute",
        config="prime_cli.command_configs:RegistryCheckImageConfig",
        positionals=("image",),
    ),
    Command(
        path=("registry", "list"),
        callback="prime_cli.commands.registry:list_registry_credentials",
        summary="List registry credentials available to the current user.",
        section="Compute",
        config="prime_cli.command_configs:RegistryListConfig",
    ),
    Command(
        path=("sandbox", "create"),
        callback="prime_cli.commands.sandbox:create",
        summary="Create a new sandbox",
        section="Compute",
        config="prime_cli.command_configs:SandboxCreateConfig",
        positionals=("docker_image",),
    ),
    Command(
        path=("sandbox", "delete"),
        callback="prime_cli.commands.sandbox:delete",
        summary="Delete one or more sandboxes by ID, by label, or all sandboxes with --all",
        section="Compute",
        config="prime_cli.command_configs:SandboxDeleteConfig",
        positionals=("sandbox_ids",),
    ),
    Command(
        path=("sandbox", "download"),
        callback="prime_cli.commands.sandbox:download_file",
        summary="Download a file from a sandbox",
        section="Compute",
        config="prime_cli.command_configs:SandboxDownloadConfig",
        positionals=("sandbox_id", "remote_path", "local_file"),
    ),
    Command(
        path=("sandbox", "expose"),
        callback="prime_cli.commands.sandbox:expose_port",
        summary="Expose a port from a sandbox.",
        section="Compute",
        config="prime_cli.command_configs:SandboxExposeConfig",
        positionals=("sandbox_id", "port"),
    ),
    Command(
        path=("sandbox", "get"),
        callback="prime_cli.commands.sandbox:get",
        summary="Get detailed information about a specific sandbox",
        section="Compute",
        config="prime_cli.command_configs:SandboxGetConfig",
        positionals=("sandbox_id",),
    ),
    Command(
        path=("sandbox", "list"),
        callback="prime_cli.commands.sandbox:list_sandboxes_cmd",
        summary="List your sandboxes",
        section="Compute",
        config="prime_cli.command_configs:SandboxListConfig",
    ),
    Command(
        path=("sandbox", "list-ports"),
        callback="prime_cli.commands.sandbox:list_ports",
        summary="List exposed ports for a sandbox, or all sandboxes if no ID is provided",
        section="Compute",
        config="prime_cli.command_configs:SandboxListPortsConfig",
        positionals=("sandbox_id",),
    ),
    Command(
        path=("sandbox", "logs"),
        callback="prime_cli.commands.sandbox:logs",
        summary="Get logs from a sandbox",
        section="Compute",
        config="prime_cli.command_configs:SandboxLogsConfig",
        positionals=("sandbox_id",),
    ),
    Command(
        path=("sandbox", "reset-cache"),
        callback="prime_cli.commands.sandbox:reset_cache",
        summary="Reset sandbox authentication cache",
        section="Compute",
        config="prime_cli.command_configs:SandboxResetCacheConfig",
    ),
    Command(
        path=("sandbox", "run"),
        callback="prime_cli.commands.sandbox:run",
        summary="Execute a command in a sandbox.",
        section="Compute",
        config="prime_cli.command_configs:SandboxRunConfig",
        positionals=("sandbox_id", "command"),
    ),
    Command(
        path=("sandbox", "ssh"),
        callback="prime_cli.commands.sandbox:ssh_connect",
        summary="Connect to a sandbox via SSH.",
        section="Compute",
        config="prime_cli.command_configs:SandboxSshConfig",
        positionals=("sandbox_id", "ssh_args"),
    ),
    Command(
        path=("sandbox", "unexpose"),
        callback="prime_cli.commands.sandbox:unexpose_port",
        summary="Unexpose a port from a sandbox",
        section="Compute",
        config="prime_cli.command_configs:SandboxUnexposeConfig",
        positionals=("sandbox_id", "exposure_id"),
    ),
    Command(
        path=("sandbox", "upload"),
        callback="prime_cli.commands.sandbox:upload_file",
        summary="Upload a file to a sandbox",
        section="Compute",
        config="prime_cli.command_configs:SandboxUploadConfig",
        positionals=("sandbox_id", "local_file", "remote_path"),
    ),
    Command(
        path=("secret", "create"),
        callback="prime_cli.commands.secrets:secret_create",
        summary="Create a new global secret.",
        section="Account",
        config="prime_cli.command_configs:SecretCreateConfig",
    ),
    Command(
        path=("secret", "delete"),
        callback="prime_cli.commands.secrets:secret_delete",
        summary="Delete a global secret.",
        section="Account",
        config="prime_cli.command_configs:SecretDeleteConfig",
        positionals=("secret_id",),
    ),
    Command(
        path=("secret", "get"),
        callback="prime_cli.commands.secrets:secret_get",
        summary="Get details of a specific secret.",
        section="Account",
        config="prime_cli.command_configs:SecretGetConfig",
        positionals=("secret_id",),
    ),
    Command(
        path=("secret", "list"),
        callback="prime_cli.commands.secrets:secret_list",
        summary="List your global secrets.",
        section="Account",
        config="prime_cli.command_configs:SecretListConfig",
    ),
    Command(
        path=("secret", "update"),
        callback="prime_cli.commands.secrets:secret_update",
        summary="Update an existing global secret.",
        section="Account",
        config="prime_cli.command_configs:SecretUpdateConfig",
        positionals=("secret_id",),
    ),
    Command(
        path=("switch",),
        callback="prime_cli.commands.switch:switch",
        summary="Switch between your personal account and team contexts",
        section="Account",
        config="prime_cli.command_configs:SwitchConfig",
        positionals=("target",),
    ),
    Command(
        path=("teams", "list"),
        callback="prime_cli.commands.teams:list_teams",
        summary="List teams for the current user.",
        section="Account",
        config="prime_cli.command_configs:TeamsListConfig",
    ),
    Command(
        path=("teams", "members"),
        callback="prime_cli.commands.teams:list_members",
        summary="List members of a team.",
        section="Account",
        config="prime_cli.command_configs:TeamsMembersConfig",
    ),
    Command(
        path=("train", "checkpoints"),
        callback="prime_cli.commands.rl:list_checkpoints",
        summary="List checkpoints for a run.",
        section="Lab",
        config="prime_cli.command_configs:TrainCheckpointsConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("train", "components"),
        callback="prime_cli.commands.rl:list_components",
        summary="List pods (orchestrator + env-servers) for a run.",
        section="Lab",
        config="prime_cli.command_configs:TrainComponentsConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("train", "configs"),
        callback="prime_cli.commands.rl:list_configs",
        summary="List available configuration options for Hosted Training.",
        section="Lab",
        config="prime_cli.command_configs:TrainConfigsConfig",
    ),
    Command(
        path=("train", "delete"),
        callback="prime_cli.commands.rl:delete_run",
        summary="Delete a run.",
        section="Lab",
        config="prime_cli.command_configs:TrainDeleteConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("train", "distributions"),
        callback="prime_cli.commands.rl:get_distributions",
        summary="Get reward/advantage distribution histogram for a run.",
        section="Lab",
        config="prime_cli.command_configs:TrainDistributionsConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("train", "get"),
        callback="prime_cli.commands.rl:get_run",
        summary="Get details of a specific run.",
        section="Lab",
        config="prime_cli.command_configs:TrainGetConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("train", "init"),
        callback="prime_cli.commands.rl:init_config",
        summary="Generate a template config file for a Hosted Training run.",
        section="Lab",
        config="prime_cli.command_configs:TrainInitConfig",
        positionals=("output_path",),
    ),
    Command(
        path=("train", "list"),
        callback="prime_cli.commands.rl:list_runs",
        summary="List your runs.",
        section="Lab",
        config="prime_cli.command_configs:TrainListConfig",
    ),
    Command(
        path=("train", "logs"),
        callback="prime_cli.commands.rl:get_logs",
        summary="Get logs for a run.",
        section="Lab",
        config="prime_cli.command_configs:TrainLogsConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("train", "metrics"),
        callback="prime_cli.commands.rl:get_metrics",
        summary="Get Hosted Training metrics for a run.",
        section="Lab",
        config="prime_cli.command_configs:TrainMetricsConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("train", "models"),
        callback="prime_cli.commands.rl:list_models",
        summary="List available models for Hosted Training.",
        section="Lab",
        config="prime_cli.command_configs:TrainModelsConfig",
    ),
    Command(
        path=("train", "progress"),
        callback="prime_cli.commands.rl:get_progress",
        summary="Get progress information, including which steps have samples and distributions.",
        section="Lab",
        config="prime_cli.command_configs:TrainProgressConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("train", "request"),
        callback="prime_cli.commands.rl:request_models",
        summary="Request models for Hosted Training.",
        section="Lab",
        config="prime_cli.command_configs:TrainRequestConfig",
    ),
    Command(
        path=("train", "restart"),
        callback="prime_cli.commands.rl:restart_run",
        summary="Restart a running run from its latest checkpoint.",
        section="Lab",
        config="prime_cli.command_configs:TrainRestartConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("train", "rollouts"),
        callback="prime_cli.commands.rl:get_rollouts",
        summary="Get rollout samples for a run.",
        section="Lab",
        config="prime_cli.command_configs:TrainRolloutsConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("train", "run"),
        callback="prime_cli.commands.rl:create_run",
        summary="Launch a Hosted Training run from a config file.",
        section="Lab",
        config="prime_cli.command_configs:TrainRunConfig",
        positionals=("config_path",),
    ),
    Command(
        path=("train", "stop"),
        callback="prime_cli.commands.rl:stop_run",
        summary="Stop a run.",
        section="Lab",
        config="prime_cli.command_configs:TrainStopConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("train", "usage"),
        callback="prime_cli.commands.usage:run_usage_command",
        summary="Show token usage and price for a single training run.",
        section="Lab",
        config="prime_cli.command_configs:TrainUsageConfig",
        positionals=("run_id",),
    ),
    Command(
        path=("tunnel", "list"),
        callback="prime_cli.commands.tunnel:list_tunnels",
        summary="List active tunnels.",
        section="Compute",
        config="prime_cli.command_configs:TunnelListConfig",
    ),
    Command(
        path=("tunnel", "start"),
        callback="prime_cli.commands.tunnel:start_tunnel",
        summary="Start a tunnel to expose a local port.",
        section="Compute",
        config="prime_cli.command_configs:TunnelStartConfig",
    ),
    Command(
        path=("tunnel", "status"),
        callback="prime_cli.commands.tunnel:tunnel_status",
        summary="Get status of a specific tunnel.",
        section="Compute",
        config="prime_cli.command_configs:TunnelStatusConfig",
        positionals=("tunnel_id",),
    ),
    Command(
        path=("tunnel", "stop"),
        callback="prime_cli.commands.tunnel:stop_tunnel",
        summary="Stop and delete one or more tunnels.",
        section="Compute",
        config="prime_cli.command_configs:TunnelStopConfig",
        positionals=("tunnel_ids",),
    ),
    Command(
        path=("upgrade",),
        callback="prime_cli.commands.upgrade:upgrade",
        summary="Upgrade the Prime CLI to the latest version",
        section="Account",
        config="prime_cli.command_configs:UpgradeConfig",
    ),
    Command(
        path=("wallet",),
        callback="prime_cli.commands.wallet:wallet_command",
        summary="Show wallet balance and most recent billing rows.",
        section="Account",
        config="prime_cli.command_configs:WalletConfig",
    ),
    Command(
        path=("whoami",),
        callback="prime_cli.commands.whoami:whoami",
        summary="Show current authenticated user and update config",
        section="Account",
        config="prime_cli.command_configs:WhoamiConfig",
    ),
)


def command_map() -> dict[tuple[str, ...], Command]:
    commands: dict[tuple[str, ...], Command] = {}
    for command in COMMANDS:
        if command.path in commands:
            path = " ".join(command.path)
            raise RuntimeError(f"duplicate Prime CLI command path: {path}")
        commands[command.path] = command
    return commands
