"""Declarative Prime CLI command registry."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Command:
    path: tuple[str, ...]
    module: str
    summary: str
    section: str
    raw: bool = False


GROUPS: dict[tuple[str, ...], str] = {
    ("availability",): "Check GPU availability and pricing.",
    ("config",): "Configure the Prime CLI.",
    ("deployments",): "Manage adapter deployments.",
    ("disks",): "Manage persistent storage.",
    ("env",): "Manage Verifiers environments and Hub publishing.",
    ("env", "action"): "Manage environment actions.",
    ("env", "secret"): "Manage environment secrets.",
    ("env", "var"): "Manage environment variables.",
    ("env", "version"): "Manage environment versions.",
    ("eval",): "Run local evaluations or manage hosted evaluations.",
    ("gepa",): "Run GEPA prompt optimization with Verifiers.",
    ("images",): "Manage container images in the Prime registry.",
    ("inference",): "Use Prime Inference.",
    ("lab",): "Manage the Prime Lab workspace.",
    ("pods",): "Manage compute pods.",
    ("registry",): "Manage registry credentials and private images.",
    ("sandbox",): "Manage sandboxes.",
    ("secret",): "Manage global secrets.",
    ("teams",): "Inspect teams and memberships.",
    ("train",): "Launch and manage Hosted Training runs.",
    ("tunnel",): "Manage tunnels for exposing local services.",
}


COMMANDS: tuple[Command, ...] = (
    Command(
        path=("availability", "disks"),
        module="prime_cli.leaves.availability.disks",
        summary="List available disks",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("availability", "gpu-types"),
        module="prime_cli.leaves.availability.gpu_types",
        summary="List available GPU types",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("availability", "list"),
        module="prime_cli.leaves.availability.list",
        summary="List available GPU resources",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("config", "delete"),
        module="prime_cli.leaves.config.delete",
        summary="Delete a saved environment",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "envs"),
        module="prime_cli.leaves.config.envs",
        summary="List available environments",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "remove-team-id"),
        module="prime_cli.leaves.config.remove_team_id",
        summary="Remove team ID to use personal account",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "reset"),
        module="prime_cli.leaves.config.reset",
        summary="Reset configuration to defaults",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "save"),
        module="prime_cli.leaves.config.save",
        summary="Save current config as environment (including API key)",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "set-api-key"),
        module="prime_cli.leaves.config.set_api_key",
        summary="Set your API key (prompts securely if not provided)",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "set-base-url"),
        module="prime_cli.leaves.config.set_base_url",
        summary="Set the API base URL (prompts if not provided)",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "set-frontend-url"),
        module="prime_cli.leaves.config.set_frontend_url",
        summary="Set the frontend URL (prompts if not provided)",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "set-inference-url"),
        module="prime_cli.leaves.config.set_inference_url",
        summary="Set the inference URL (prompts if not provided)",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "set-share-resources-with-team"),
        module="prime_cli.leaves.config.set_share_resources_with_team",
        summary="Set whether to automatically share new resources with all team members",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "set-ssh-key-path"),
        module="prime_cli.leaves.config.set_ssh_key_path",
        summary="Set the SSH private key path",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "set-team-id"),
        module="prime_cli.leaves.config.set_team_id",
        summary="Set your team ID.",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "use"),
        module="prime_cli.leaves.config.use",
        summary="Switch to a different environment",
        section="Account",
        raw=False,
    ),
    Command(
        path=("config", "view"),
        module="prime_cli.leaves.config.view",
        summary="View current configuration",
        section="Account",
        raw=False,
    ),
    Command(
        path=("deployments", "create"),
        module="prime_cli.leaves.deployments.create",
        summary="Deploy a model for inference.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("deployments", "delete"),
        module="prime_cli.leaves.deployments.delete",
        summary="Unload a model from inference.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("deployments", "list"),
        module="prime_cli.leaves.deployments.list",
        summary="List adapters and their deployment status.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("disks", "create"),
        module="prime_cli.leaves.disks.create",
        summary="Create a new storage disk",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("disks", "get"),
        module="prime_cli.leaves.disks.get",
        summary="Get detailed information about a specific disk",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("disks", "list"),
        module="prime_cli.leaves.disks.list",
        summary="List your persistent disks",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("disks", "terminate"),
        module="prime_cli.leaves.disks.terminate",
        summary="Terminate a disk",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("disks", "update"),
        module="prime_cli.leaves.disks.update",
        summary="Update a disk's name",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("env", "action", "list"),
        module="prime_cli.leaves.env.action.list",
        summary="List actions (CI jobs) for an environment.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "action", "logs"),
        module="prime_cli.leaves.env.action.logs",
        summary="Get logs for a specific action.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "action", "retry"),
        module="prime_cli.leaves.env.action.retry",
        summary="Retry an action (integration test) for an environment.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "build"),
        module="prime_cli.leaves.env.build",
        summary="Build an OpenEnv-backed environment image.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "delete"),
        module="prime_cli.leaves.env.delete",
        summary="Delete an entire environment from the environments hub",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "info"),
        module="prime_cli.leaves.env.info",
        summary="Show environment details and installation commands",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "init"),
        module="prime_cli.leaves.env.init",
        summary="Initialize a V1 or V0 environment with Verifiers.",
        section="Lab",
        raw=True,
    ),
    Command(
        path=("env", "inspect"),
        module="prime_cli.leaves.env.inspect",
        summary="Inspect environment source without downloading the archive locally.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "install"),
        module="prime_cli.leaves.env.install",
        summary="Install a verifiers environment.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "list"),
        module="prime_cli.leaves.env.list",
        summary="List environments from the hub.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "pull"),
        module="prime_cli.leaves.env.pull",
        summary="Pull environment for local inspection",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "push"),
        module="prime_cli.leaves.env.push",
        summary="Push environment to registry",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "secret", "create"),
        module="prime_cli.leaves.env.secret.create",
        summary="Create an environment-specific secret.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "secret", "delete"),
        module="prime_cli.leaves.env.secret.delete",
        summary="Delete an environment-specific secret.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "secret", "link"),
        module="prime_cli.leaves.env.secret.link",
        summary="Link a global secret to an environment.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "secret", "list"),
        module="prime_cli.leaves.env.secret.list",
        summary="List all secrets for an environment.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "secret", "unlink"),
        module="prime_cli.leaves.env.secret.unlink",
        summary="Unlink a global secret from an environment.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "secret", "update"),
        module="prime_cli.leaves.env.secret.update",
        summary="Update an environment-specific secret.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "serve"),
        module="prime_cli.leaves.env.serve",
        summary="Serve a V1 or V0 environment with Verifiers.",
        section="Lab",
        raw=True,
    ),
    Command(
        path=("env", "status"),
        module="prime_cli.leaves.env.status",
        summary="Show action status for an environment.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "uninstall"),
        module="prime_cli.leaves.env.uninstall",
        summary="Uninstall an environment distribution with uv.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "validate"),
        module="prime_cli.leaves.env.validate",
        summary="Run a taskset's model-free validation with Verifiers.",
        section="Lab",
        raw=True,
    ),
    Command(
        path=("env", "var", "create"),
        module="prime_cli.leaves.env.var.create",
        summary="Create an environment variable.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "var", "delete"),
        module="prime_cli.leaves.env.var.delete",
        summary="Delete an environment variable.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "var", "list"),
        module="prime_cli.leaves.env.var.list",
        summary="List all variables for an environment.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "var", "update"),
        module="prime_cli.leaves.env.var.update",
        summary="Update an environment variable.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "version", "delete"),
        module="prime_cli.leaves.env.version.delete",
        summary="Delete an environment version by content hash",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("env", "version", "list"),
        module="prime_cli.leaves.env.version.list",
        summary="List all versions of an environment",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("eval", "get"),
        module="prime_cli.leaves.eval.get",
        summary="Show evaluation details.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("eval", "list"),
        module="prime_cli.leaves.eval.list",
        summary="List evaluations.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("eval", "logs"),
        module="prime_cli.leaves.eval.logs",
        summary="Get logs for a hosted evaluation.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("eval", "push"),
        module="prime_cli.leaves.eval.push",
        summary="Push native or legacy evaluation data to Prime Evals.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("eval", "run"),
        module="prime_cli.leaves.eval.run",
        summary="Run a local V1 or V0 evaluation with Verifiers",
        section="Lab",
        raw=True,
    ),
    Command(
        path=("eval", "samples"),
        module="prime_cli.leaves.eval.samples",
        summary="",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("eval", "stop"),
        module="prime_cli.leaves.eval.stop",
        summary="Stop a running hosted evaluation.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("eval", "submit"),
        module="prime_cli.leaves.eval.submit",
        summary="Submit a hosted V0 evaluation",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("eval", "view"),
        module="prime_cli.leaves.eval.view",
        summary="Launch the interactive evaluation viewer.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("feedback",),
        module="prime_cli.leaves.feedback",
        summary="Submit feedback about Prime Intellect.",
        section="Account",
        raw=False,
    ),
    Command(
        path=("fork",),
        module="prime_cli.leaves.fork",
        summary="Fork a public environment into your Prime Intellect namespace.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("gepa", "run"),
        module="prime_cli.leaves.gepa.run",
        summary="Run Verifiers' native GEPA command.",
        section="Lab",
        raw=True,
    ),
    Command(
        path=("images", "delete"),
        module="prime_cli.leaves.images.delete",
        summary="Delete an image from your registry.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("images", "list"),
        module="prime_cli.leaves.images.list",
        summary="List all images you've pushed to Prime Intellect registry.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("images", "publish"),
        module="prime_cli.leaves.images.publish",
        summary="Make an image public so other Prime users can run it.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("images", "push"),
        module="prime_cli.leaves.images.push",
        summary="Build and push a Docker image to Prime Intellect registry.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("images", "unpublish"),
        module="prime_cli.leaves.images.unpublish",
        summary="Make a public image private again.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("inference", "chat"),
        module="prime_cli.leaves.inference.chat",
        summary="Send a one-shot chat message to a Prime Inference model.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("inference", "models"),
        module="prime_cli.leaves.inference.models",
        summary="List available models from Prime Inference (/v1/models).",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("lab", "doctor"),
        module="prime_cli.leaves.lab.doctor",
        summary="Check a Lab workspace.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("lab", "hygiene"),
        module="prime_cli.leaves.lab.hygiene",
        summary="Check cheap Lab git hygiene.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("lab", "mcp"),
        module="prime_cli.leaves.lab.mcp",
        summary="Run the Lab MCP server over stdio.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("lab", "register-github"),
        module="prime_cli.leaves.lab.register_github",
        summary="Write the GitHub workflow for Lab git hygiene.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("lab", "setup"),
        module="prime_cli.leaves.lab.setup",
        summary="Set up a Lab workspace.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("lab", "sync"),
        module="prime_cli.leaves.lab.sync",
        summary="Refresh Lab skills and local agent guidance.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("lab", "view"),
        module="prime_cli.leaves.lab.view",
        summary="Launch the interactive Lab viewer.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("login",),
        module="prime_cli.leaves.login",
        summary="Login to Prime Intellect",
        section="Account",
        raw=False,
    ),
    Command(
        path=("logout",),
        module="prime_cli.leaves.logout",
        summary="Log out of Prime Intellect",
        section="Account",
        raw=False,
    ),
    Command(
        path=("pods", "create"),
        module="prime_cli.leaves.pods.create",
        summary="Create a new pod with an interactive setup process",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("pods", "history"),
        module="prime_cli.leaves.pods.history",
        summary="List your pods history (terminated pods)",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("pods", "list"),
        module="prime_cli.leaves.pods.list",
        summary="List your running pods",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("pods", "ssh"),
        module="prime_cli.leaves.pods.ssh",
        summary="SSH / connect to a pod using configured SSH key",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("pods", "status"),
        module="prime_cli.leaves.pods.status",
        summary="Get detailed status of a specific pod",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("pods", "terminate"),
        module="prime_cli.leaves.pods.terminate",
        summary="Terminate a pod",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("registry", "check-image"),
        module="prime_cli.leaves.registry.check_image",
        summary="Verify that an image is accessible (optionally using registry credentials).",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("registry", "list"),
        module="prime_cli.leaves.registry.list",
        summary="List registry credentials available to the current user.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "create"),
        module="prime_cli.leaves.sandbox.create",
        summary="Create a new sandbox",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "delete"),
        module="prime_cli.leaves.sandbox.delete",
        summary="Delete one or more sandboxes by ID, by label, or all sandboxes with --all",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "download"),
        module="prime_cli.leaves.sandbox.download",
        summary="Download a file from a sandbox",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "expose"),
        module="prime_cli.leaves.sandbox.expose",
        summary="Expose a port from a sandbox.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "get"),
        module="prime_cli.leaves.sandbox.get",
        summary="Get detailed information about a specific sandbox",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "list"),
        module="prime_cli.leaves.sandbox.list",
        summary="List your sandboxes",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "list-ports"),
        module="prime_cli.leaves.sandbox.list_ports",
        summary="List exposed ports for a sandbox, or all sandboxes if no ID is provided",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "logs"),
        module="prime_cli.leaves.sandbox.logs",
        summary="Get logs from a sandbox",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "reset-cache"),
        module="prime_cli.leaves.sandbox.reset_cache",
        summary="Reset sandbox authentication cache",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "run"),
        module="prime_cli.leaves.sandbox.run",
        summary="Execute a command in a sandbox.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "ssh"),
        module="prime_cli.leaves.sandbox.ssh",
        summary="Connect to a sandbox via SSH.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "unexpose"),
        module="prime_cli.leaves.sandbox.unexpose",
        summary="Unexpose a port from a sandbox",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("sandbox", "upload"),
        module="prime_cli.leaves.sandbox.upload",
        summary="Upload a file to a sandbox",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("secret", "create"),
        module="prime_cli.leaves.secret.create",
        summary="Create a new global secret.",
        section="Account",
        raw=False,
    ),
    Command(
        path=("secret", "delete"),
        module="prime_cli.leaves.secret.delete",
        summary="Delete a global secret.",
        section="Account",
        raw=False,
    ),
    Command(
        path=("secret", "get"),
        module="prime_cli.leaves.secret.get",
        summary="Get details of a specific secret.",
        section="Account",
        raw=False,
    ),
    Command(
        path=("secret", "list"),
        module="prime_cli.leaves.secret.list",
        summary="List your global secrets.",
        section="Account",
        raw=False,
    ),
    Command(
        path=("secret", "update"),
        module="prime_cli.leaves.secret.update",
        summary="Update an existing global secret.",
        section="Account",
        raw=False,
    ),
    Command(
        path=("switch",),
        module="prime_cli.leaves.switch",
        summary="Switch between your personal account and team contexts",
        section="Account",
        raw=False,
    ),
    Command(
        path=("teams", "list"),
        module="prime_cli.leaves.teams.list",
        summary="List teams for the current user.",
        section="Account",
        raw=False,
    ),
    Command(
        path=("teams", "members"),
        module="prime_cli.leaves.teams.members",
        summary="List members of a team.",
        section="Account",
        raw=False,
    ),
    Command(
        path=("train", "checkpoints"),
        module="prime_cli.leaves.train.checkpoints",
        summary="List checkpoints for a run.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "components"),
        module="prime_cli.leaves.train.components",
        summary="List pods (orchestrator + env-servers) for a run.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "configs"),
        module="prime_cli.leaves.train.configs",
        summary="List available configuration options for Hosted Training.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "delete"),
        module="prime_cli.leaves.train.delete",
        summary="Delete a run.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "distributions"),
        module="prime_cli.leaves.train.distributions",
        summary="Get reward/advantage distribution histogram for a run.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "get"),
        module="prime_cli.leaves.train.get",
        summary="Get details of a specific run.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "init"),
        module="prime_cli.leaves.train.init",
        summary="Generate a template config file for a Hosted Training run.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "list"),
        module="prime_cli.leaves.train.list",
        summary="List your runs.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "logs"),
        module="prime_cli.leaves.train.logs",
        summary="Get logs for a run.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "metrics"),
        module="prime_cli.leaves.train.metrics",
        summary="Get Hosted Training metrics for a run.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "models"),
        module="prime_cli.leaves.train.models",
        summary="List available models for Hosted Training.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "progress"),
        module="prime_cli.leaves.train.progress",
        summary="Get progress information, including which steps have samples and distributions.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "request"),
        module="prime_cli.leaves.train.request",
        summary="Request models for Hosted Training.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "restart"),
        module="prime_cli.leaves.train.restart",
        summary="Restart a running run from its latest checkpoint.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "rollouts"),
        module="prime_cli.leaves.train.rollouts",
        summary="Get rollout samples for a run.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "run"),
        module="prime_cli.leaves.train.run",
        summary="Launch a Hosted Training run from a config file.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "stop"),
        module="prime_cli.leaves.train.stop",
        summary="Stop a run.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("train", "usage"),
        module="prime_cli.leaves.train.usage",
        summary="Show token usage and price for a single training run.",
        section="Lab",
        raw=False,
    ),
    Command(
        path=("tunnel", "list"),
        module="prime_cli.leaves.tunnel.list",
        summary="List active tunnels.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("tunnel", "start"),
        module="prime_cli.leaves.tunnel.start",
        summary="Start a tunnel to expose a local port.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("tunnel", "status"),
        module="prime_cli.leaves.tunnel.status",
        summary="Get status of a specific tunnel.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("tunnel", "stop"),
        module="prime_cli.leaves.tunnel.stop",
        summary="Stop and delete one or more tunnels.",
        section="Compute",
        raw=False,
    ),
    Command(
        path=("upgrade",),
        module="prime_cli.leaves.upgrade",
        summary="Upgrade the Prime CLI to the latest version",
        section="Account",
        raw=False,
    ),
    Command(
        path=("wallet",),
        module="prime_cli.leaves.wallet",
        summary="Show wallet balance and most recent billing rows.",
        section="Account",
        raw=False,
    ),
    Command(
        path=("whoami",),
        module="prime_cli.leaves.whoami",
        summary="Show current authenticated user and update config",
        section="Account",
        raw=False,
    ),
)


def command_map() -> dict[tuple[str, ...], Command]:
    commands = {command.path: command for command in COMMANDS}
    if len(commands) != len(COMMANDS):
        raise RuntimeError("duplicate Prime CLI command path")
    return commands
