import os
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from prime_tunnel import Config, Tunnel, TunnelClient
from prime_tunnel.exceptions import TunnelError, TunnelTimeoutError
from prime_tunnel.models import TunnelInfo


def test_tunnel_init():
    """Test Tunnel initialization."""
    tunnel = Tunnel(local_port=8080)
    assert tunnel.local_port == 8080
    assert tunnel.local_addr == "127.0.0.1"
    assert tunnel.name is None
    assert not tunnel.is_running


def test_tunnel_init_with_name():
    """Test Tunnel initialization with name."""
    tunnel = Tunnel(local_port=9000, name="my-tunnel")
    assert tunnel.local_port == 9000
    assert tunnel.name == "my-tunnel"


def test_tunnel_init_with_labels():
    """Test Tunnel initialization with labels."""
    tunnel = Tunnel(local_port=9000, labels=["dev", "api"])
    assert tunnel.labels == ["dev", "api"]


def test_tunnel_init_with_http_auth():
    """Test Tunnel initialization with HTTP basic auth username."""
    tunnel = Tunnel(local_port=9000, http_user="alice")
    assert tunnel.http_user == "alice"
    # Password is generated by the backend; unavailable before start()
    assert tunnel.http_password is None


def test_tunnel_info_accepts_labels():
    """Test TunnelInfo carries labels and status metadata."""
    tunnel_info = TunnelInfo(
        tunnel_id="t-test123",
        hostname="t-test123.tunnel.example.com",
        url="https://t-test123.tunnel.example.com",
        frp_token="tok",
        server_host="frp.example.com",
        server_port=7000,
        expires_at=datetime.now(timezone.utc),
        labels=["dev"],
        status="CONNECTED",
    )
    assert tunnel_info.labels == ["dev"]
    assert tunnel_info.status == "CONNECTED"


def test_config_default_base_url():
    """Test Config default base URL."""
    config = Config()
    assert config.DEFAULT_BASE_URL == "https://api.primeintellect.ai"


def test_config_base_url_from_env(monkeypatch):
    """Test Config base_url from environment variable."""
    monkeypatch.setenv("PRIME_BASE_URL", "https://custom.example.com")
    config = Config()
    assert config.base_url == "https://custom.example.com"


def test_config_base_url_strips_api_v1(monkeypatch):
    """Test Config strips /api/v1 from base URL."""
    monkeypatch.setenv("PRIME_BASE_URL", "https://example.com/api/v1")
    config = Config()
    assert config.base_url == "https://example.com"


def test_config_api_key_from_env(monkeypatch):
    """Test Config api_key from environment variable."""
    monkeypatch.setenv("PRIME_API_KEY", "test-key-123")
    config = Config()
    assert config.api_key == "test-key-123"


def test_config_bin_dir():
    """Test Config bin_dir property."""
    config = Config()
    assert config.bin_dir.name == "bin"
    assert ".prime" in str(config.bin_dir)


def test_tunnel_client_init(monkeypatch, tmp_path):
    """Test TunnelClient initialization."""
    monkeypatch.setenv("HOME", str(tmp_path))
    monkeypatch.delenv("PRIME_API_BASE_URL", raising=False)
    monkeypatch.delenv("PRIME_BASE_URL", raising=False)
    client = TunnelClient(api_key="test-key")
    assert client.api_key == "test-key"
    assert client.base_url == Config.DEFAULT_BASE_URL


def _make_started_tunnel() -> Tunnel:
    """Create a Tunnel that looks like it was started."""
    tunnel = Tunnel(local_port=8080)
    tunnel._started = True
    tunnel._process = MagicMock()
    tunnel._tunnel_info = TunnelInfo(
        tunnel_id="t-test123",
        hostname="t-test123.tunnel.example.com",
        url="https://t-test123.tunnel.example.com",
        frp_token="tok",
        server_host="frp.example.com",
        server_port=7000,
        expires_at=datetime.now(timezone.utc),
    )
    tunnel._config_file = MagicMock()
    tunnel._config_file.exists.return_value = True
    return tunnel


def test_sync_stop_noop_when_not_started():
    tunnel = Tunnel(local_port=8080)
    tunnel.sync_stop()  # should not raise


def test_sync_stop_terminates_process_and_deletes_registration():
    tunnel = _make_started_tunnel()
    process_mock = tunnel._process

    with patch("prime_tunnel.tunnel.httpx.delete") as mock_delete:
        tunnel.sync_stop()

    process_mock.terminate.assert_called_once()
    mock_delete.assert_called_once()
    assert "t-test123" in mock_delete.call_args[0][0]
    assert tunnel._started is False
    assert tunnel._tunnel_info is None
    assert tunnel._process is None


def test_sync_stop_kills_on_timeout():
    tunnel = _make_started_tunnel()
    process_mock = tunnel._process
    import subprocess

    process_mock.wait.side_effect = subprocess.TimeoutExpired(cmd="frpc", timeout=5)

    with patch("prime_tunnel.tunnel.httpx.delete"):
        tunnel.sync_stop()

    process_mock.terminate.assert_called_once()
    process_mock.kill.assert_called_once()
    assert tunnel._started is False


def test_sync_stop_survives_delete_failure():
    tunnel = _make_started_tunnel()

    with patch("prime_tunnel.tunnel.httpx.delete", side_effect=Exception("network")):
        tunnel.sync_stop()  # should not raise

    assert tunnel._started is False
    assert tunnel._tunnel_info is None


# -- check_registered tests --


@pytest.mark.asyncio
async def test_check_registered_returns_true():
    tunnel = _make_started_tunnel()
    tunnel._client = AsyncMock()
    tunnel._client.get_tunnel.return_value = tunnel._tunnel_info
    assert await tunnel.check_registered() is True
    tunnel._client.get_tunnel.assert_awaited_once_with("t-test123")


@pytest.mark.asyncio
async def test_check_registered_returns_false_on_404():
    tunnel = _make_started_tunnel()
    tunnel._client = AsyncMock()
    tunnel._client.get_tunnel.return_value = None
    assert await tunnel.check_registered() is False


@pytest.mark.asyncio
async def test_check_registered_returns_false_when_no_tunnel_info():
    tunnel = Tunnel(local_port=8080)
    assert await tunnel.check_registered() is False


@pytest.mark.asyncio
async def test_check_registered_propagates_api_errors():
    tunnel = _make_started_tunnel()
    tunnel._client = AsyncMock()
    tunnel._client.get_tunnel.side_effect = TunnelTimeoutError("timeout")
    with pytest.raises(TunnelTimeoutError):
        await tunnel.check_registered()


@pytest.mark.asyncio
async def test_client_create_tunnel_sends_labels(monkeypatch):
    client = TunnelClient(api_key="test-key")
    captured = {}

    async def fake_request(method, url, json=None, params=None):
        captured["method"] = method
        captured["url"] = url
        captured["json"] = json
        captured["params"] = params
        return MagicMock(status_code=201)

    async def fake_handle_response(response, operation):
        return {
            "tunnel_id": "t-test123",
            "hostname": "t-test123.tunnel.example.com",
            "url": "https://t-test123.tunnel.example.com",
            "frp_token": "tok",
            "binding_secret": "secret",
            "server_host": "frp.example.com",
            "server_port": 7000,
            "expires_at": datetime.now(timezone.utc).isoformat(),
            "labels": ["dev"],
        }

    monkeypatch.setattr(client, "_request_with_retry", fake_request)
    monkeypatch.setattr(client, "_handle_response", fake_handle_response)

    tunnel_info = await client.create_tunnel(local_port=8765, labels=["dev"])

    assert captured["json"]["labels"] == ["dev"]
    assert tunnel_info.labels == ["dev"]


@pytest.mark.asyncio
async def test_client_create_tunnel_sends_http_auth(monkeypatch):
    client = TunnelClient(api_key="test-key")
    captured = {}

    async def fake_request(method, url, json=None, params=None):
        captured["json"] = json
        return MagicMock(status_code=201)

    async def fake_handle_response(response, operation):
        return {
            "tunnel_id": "t-test123",
            "hostname": "t-test123.tunnel.example.com",
            "url": "https://t-test123.tunnel.example.com",
            "frp_token": "tok",
            "binding_secret": "secret",
            "server_host": "frp.example.com",
            "server_port": 7000,
            "expires_at": datetime.now(timezone.utc).isoformat(),
            "labels": [],
            "http_user": "alice",
            "http_password": "s3cret",
        }

    monkeypatch.setattr(client, "_request_with_retry", fake_request)
    monkeypatch.setattr(client, "_handle_response", fake_handle_response)

    tunnel_info = await client.create_tunnel(local_port=8765, http_user="alice")

    assert captured["json"]["http_user"] == "alice"
    # The password is never client-supplied; only the backend generates it.
    assert "http_password" not in captured["json"]
    assert tunnel_info.http_user == "alice"
    assert tunnel_info.http_password == "s3cret"


@pytest.mark.asyncio
async def test_client_list_tunnels_uses_plural_labels_param(monkeypatch):
    client = TunnelClient(api_key="test-key")
    captured = {}

    async def fake_request(method, url, json=None, params=None):
        captured["method"] = method
        captured["params"] = params
        return MagicMock(status_code=200)

    async def fake_handle_response(response, operation):
        return {"tunnels": []}

    monkeypatch.setattr(client, "_idempotent_request_with_retry", fake_request)
    monkeypatch.setattr(client, "_handle_response", fake_handle_response)

    tunnels = await client.list_tunnels(labels=["dev"])

    assert tunnels == []
    assert captured["params"]["labels"] == ["dev"]
    assert "label" not in captured["params"]


@pytest.mark.asyncio
async def test_client_bulk_delete_by_labels(monkeypatch):
    client = TunnelClient(api_key="test-key")
    captured = {}

    async def fake_request(method, url, json=None, params=None):
        captured["method"] = method
        captured["json"] = json
        return MagicMock(status_code=200)

    async def fake_handle_response(response, operation):
        return {"succeeded": ["t-test123"], "failed": [], "message": "ok"}

    monkeypatch.setattr(client, "_idempotent_request_with_retry", fake_request)
    monkeypatch.setattr(client, "_handle_response", fake_handle_response)

    result = await client.bulk_delete_tunnels(labels=["dev"], team_id="team-1")

    assert captured["json"]["labels"] == ["dev"]
    assert captured["json"]["teamId"] == "team-1"
    assert "team_id" not in captured["json"]
    assert result["succeeded"] == ["t-test123"]


@pytest.mark.asyncio
async def test_client_bulk_delete_ids_does_not_default_configured_team(monkeypatch):
    client = TunnelClient(api_key="test-key")
    captured = {}
    client.config.config["team_id"] = "team-from-config"

    async def fake_request(method, url, json=None, params=None):
        captured["method"] = method
        captured["json"] = json
        return MagicMock(status_code=200)

    async def fake_handle_response(response, operation):
        return {"succeeded": ["t-test123"], "failed": [], "message": "ok"}

    monkeypatch.setattr(client, "_idempotent_request_with_retry", fake_request)
    monkeypatch.setattr(client, "_handle_response", fake_handle_response)

    result = await client.bulk_delete_tunnels(tunnel_ids=["t-personal"])

    assert "teamId" not in captured["json"]
    assert "team_id" not in captured["json"]
    assert captured["json"]["tunnel_ids"] == ["t-personal"]
    assert result["succeeded"] == ["t-test123"]


@pytest.mark.asyncio
async def test_client_bulk_delete_all_users_requires_team_id(monkeypatch):
    client = TunnelClient(api_key="test-key")
    client.config.config.pop("team_id", None)
    monkeypatch.delenv("PRIME_TEAM_ID", raising=False)

    with pytest.raises(TunnelError, match="all_users requires a team ID"):
        await client.bulk_delete_tunnels(labels=["dev"], all_users=True)


@pytest.mark.asyncio
async def test_client_bulk_delete_by_status(monkeypatch):
    client = TunnelClient(api_key="test-key")
    captured = {}

    async def fake_request(method, url, json=None, params=None):
        captured["method"] = method
        captured["json"] = json
        return MagicMock(status_code=200)

    async def fake_handle_response(response, operation):
        return {"succeeded": ["t-test123"], "failed": [], "message": "ok"}

    monkeypatch.setattr(client, "_idempotent_request_with_retry", fake_request)
    monkeypatch.setattr(client, "_handle_response", fake_handle_response)

    result = await client.bulk_delete_tunnels(status="disconnected", user_id="user-1")

    assert captured["json"]["status"] == "disconnected"
    assert captured["json"]["userId"] == "user-1"
    assert "tunnel_ids" not in captured["json"]
    assert result["succeeded"] == ["t-test123"]


@pytest.mark.asyncio
async def test_client_bulk_delete_status_rejects_tunnel_ids():
    client = TunnelClient(api_key="test-key")

    with pytest.raises(TunnelError, match="status cannot be combined with tunnel_ids"):
        await client.bulk_delete_tunnels(tunnel_ids=["t-1"], status="disconnected")


# -- startup login retry tests --


def _frpc_line(level: str, msg: str) -> str:
    return f"2026-07-28 00:00:00.000 [{level}] [client/service.go:319] {msg}"


def test_scan_startup_line_connected():
    from prime_tunnel.tunnel import _scan_startup_line

    line = _frpc_line("I", "[t-test123] start proxy success")
    assert _scan_startup_line(line) == "connected"


def test_scan_startup_line_transient_failures_are_not_fatal():
    from prime_tunnel.tunnel import _scan_startup_line

    transient = [
        _frpc_line("W", "connect to server error: dial tcp 1.2.3.4:7000: i/o timeout"),
        _frpc_line("W", "connect to server error: Tunnel validation failed"),
        _frpc_line("W", "login to the server failed: EOF"),
    ]
    for line in transient:
        assert _scan_startup_line(line) is None


def test_scan_startup_line_fatal_rejections():
    from prime_tunnel.tunnel import _scan_startup_line

    fatal = [
        _frpc_line("W", "connect to server error: Tunnel is inactive"),
        _frpc_line("W", "connect to server error: Tunnel not registered"),
        _frpc_line("W", "connect to server error: Invalid binding secret"),
        _frpc_line("W", "connect to server error: Invalid authentication token"),
        _frpc_line(
            "W", "login to the server failed: token in login doesn't match token from configuration"
        ),
    ]
    for line in fatal:
        assert _scan_startup_line(line) == "fatal"


def test_scan_startup_line_ignores_unrelated_lines():
    from prime_tunnel.tunnel import _scan_startup_line

    assert _scan_startup_line(_frpc_line("I", "try to connect to server...")) is None
    # Rejection reason without a login/connect failure marker is not fatal
    assert _scan_startup_line(_frpc_line("I", "tunnel is inactive")) is None


def test_frpc_config_disables_login_fail_exit(monkeypatch, tmp_path):
    monkeypatch.setattr(Path, "home", lambda: tmp_path)
    tunnel = _make_started_tunnel()
    config_file = tunnel._write_frpc_config()
    content = config_file.read_text()
    assert "loginFailExit = false" in content
    assert 'auth.token = "tok"' in content


def _make_fake_frpc(lines: list[str]):
    """Fake Popen whose stdout is a real pipe (fcntl-compatible) fed with lines."""
    read_fd, write_fd = os.pipe()
    stdout = os.fdopen(read_fd, "r")
    for line in lines:
        os.write(write_fd, (line + "\n").encode())

    process = MagicMock()
    process.poll.return_value = None
    process.stdout = stdout
    process.stderr = None
    return process, write_fd


@pytest.mark.asyncio
async def test_wait_for_connection_rides_out_transient_failure():
    tunnel = Tunnel(local_port=8080, connection_timeout=5.0)
    process, write_fd = _make_fake_frpc(
        [
            _frpc_line("W", "connect to server error: dial tcp 1.2.3.4:7000: i/o timeout"),
            _frpc_line("I", "[t-test123] start proxy success"),
        ]
    )
    tunnel._process = process
    try:
        await tunnel._wait_for_connection()  # should not raise
    finally:
        os.close(write_fd)
        process.stdout.close()


@pytest.mark.asyncio
async def test_wait_for_connection_fails_fast_on_rejection():
    from prime_tunnel.exceptions import TunnelConnectionError

    tunnel = Tunnel(local_port=8080, connection_timeout=5.0)
    process, write_fd = _make_fake_frpc(
        [_frpc_line("W", "connect to server error: Tunnel is inactive")]
    )
    tunnel._process = process
    try:
        with pytest.raises(TunnelConnectionError, match="Tunnel is inactive"):
            await tunnel._wait_for_connection()
    finally:
        os.close(write_fd)
        process.stdout.close()


@pytest.mark.asyncio
async def test_wait_for_connection_times_out_on_persistent_transient_failure():
    tunnel = Tunnel(local_port=8080, connection_timeout=0.5)
    process, write_fd = _make_fake_frpc(
        [_frpc_line("W", "connect to server error: dial tcp 1.2.3.4:7000: i/o timeout")]
    )
    tunnel._process = process
    try:
        with pytest.raises(TunnelTimeoutError):
            await tunnel._wait_for_connection()
    finally:
        os.close(write_fd)
        process.stdout.close()
