project = "debug_7B_zero_band"

model_name = "7B"
model_type = "llama2"

[hardware]
micro_batch_size = 64
reshard_after_forward = false

[train]
batch_size = 512

[data]
seq_length = 1024
dataset_name_or_paths = "datasets/fineweb-edu"
