name_model = "13B"
project = "debug_13B_zero_band"

[train]
micro_bs = 1
ac_ckpt = true

[optim]
batch_size = 1024 #2M tokens bs
warmup_steps = 1000
total_steps = 88_000

[optim.optim]
lr = 3e-4

[data]
seq_length = 2048