name_model = "1B"
project = "debug_1B_zero_band"

[train]
micro_bs = 4  

[data]
seq_length = 8192
num_workers = 4
dataset_name_or_paths = "/data/datasets/fineweb-edu"
reverse_data_files = true

[optim]
batch_size = 256
warmup_steps = 1000
total_steps = 1_000_000_000_000
sched_type = "wsd-sqrt"
lr = 1e-4

[ckpt]
interval = 1000