project = "debug_150m_zero_band"

model_name = "debugmodel"
model_type = "llama2"

[hardware]
micro_batch_size = 4

[data]
seq_length = 8192
dataset_name_or_paths = "/data/datasets/open-web-math"
dataset_ratio = "100"
num_workers = 1

[train]
batch_size = 128

[train.optimizer]
type = "adam"

[train.lr_scheduler]
decay_type = "linear"
num_warmup_steps = 1000
lr = 3e-4
end_lr = 0.0
num_decay_steps = 80000

[pccl]
ccoip_host = "127.0.0.1:48148"