name_model = "debugmodel"
project = "debug_150m_zero_band"
type_model = "llama2"

[train]
micro_bs = 4  # change this base on the gpu

[data]
seq_length = 8192
dataset_name_or_paths = "/data/datasets/open-web-math"
dataset_ratio = "100"
num_workers = 1

[optim]
batch_size = 128
warmup_steps = 1000
total_steps = 88_000
lr = 4e-4