project = "debug_150m_zero_band"
model_name = "150M"
model_type = "llama2"

[hardware]
micro_batch_size = 64
reshard_after_forward = false

[train]
batch_size = 512

[train.lr_scheduler]
decay_type = 'cosine'
num_warmup_steps = 278
num_decay_steps = 7914 # 278 + 7914 = 8192
lr = 0.003551730141097694

[train.optimizer]
type = 'adamw'
betas1 = 0.9454835470717078
betas2 = 0.9190488086654895
weight_decay = 0.24530252977858977

[data]
seq_length = 1024
dataset_name_or_paths = "datasets/fineweb-edu"

[pccl]
ccoip_host = "127.0.0.1:48148"