model_name = "debugmodel"
model_type = "llama2"

wandb = false
log_all_ranks = true

[hardware]
micro_batch_size = 8

[train]
batch_size = 32

[train.lr_scheduler]
num_warmup_steps = 10
num_decay_steps = 1000

[data]
fake = true

[diloco]
inner_steps = 16
delayed_update = true

[pccl]
ccoip_host = "127.0.0.1:48148"