model_name = "debugmodel"
model_type = "llama2"

wandb = false

[hardware]
micro_batch_size = 8
ccl_library = 'pccl'

[train]
batch_size = 16

[train.lr_scheduler]
num_warmup_steps = 10
num_decay_steps = 10

[data]
fake = true

[diloco]
inner_steps = 5

[pccl]
ccoip_host = "127.0.0.1:48148"
peer_group = 0