name_model = "debugmodel"
project = "/tmp/debug"
metric_logger_type = "dummy"
type_model = "llama2"

[train]
micro_bs = 8

[optim]
batch_size = 16
warmup_steps = 100
total_steps = 1500

[data]
fake = true

[diloco]
inner_steps = 5

